### ISSUE TITLE
the meaning of truth sequents

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-redprl#10]
It is not entirely clear what the semantics for truth sequents should be, but here's one proposal. First, let's recall the lay of the land, since it is a little intricate.

The actual *type theory* has many judgments, one of which is `Y || Ψ != M = N in φ`, which is the parametric (in `Y`) functional (in `Ψ`) membership sequent. I will assume anyone reading this ticket knows what it means (please consult [Type Refinements for the Working Class](https://github.com/jonsterling/type-refinements-for-the-working-class) if not). In this note, I will write `Ψ ctx` rather than `Ψ refines Γ` and `φ type` rather than `φ refines τ`, just for brevity & simplicity.

The *proof theory* ("refinement logic") of Red JonPRL has a sequent judgment, written `Y || H >> φ true [ext M]`, like Nuprl (with `M` an output, and all the other symbols inputs). Whereas the `!=`-sequent is defined by the meaning explanation, the `>>`-sequent is defined inductively by a collection of sequent-calculus style rules. Of course, `>>` shall have an *intended semantics* in the type theory, with which it must be sound, but cannot be complete. `>>` is in some sense a finite approximation of `!=`—over time, we'll add more rules to refine the approximation, but we'll never actually reach a point. Now the way that the intended semantics of the proof theory works is that we impose a "postsupposition" (i.e. a condition that we can conclude from the evidence of the judgment).

So the question raised by this ticket is, What is the intended semantics for `>>`? Let us first consider the simpler case without atoms. Then, it is east: `H >> φ true [ext M]` postsupposes `H ctx`, `H != φ type` and `H != M in φ`. Recall how this differs from the usual judgments of type theory which have *presuppositions* (i.e. where the judgment only has a meaning in case the presuppositions obtain), whereas here, the judgment expresses no presupposition at all; yet, we intend to validate its postsuppositions by considering the ways in which we could come to know the judgment (in this case, inductively).

Now, we must extend the explanation to the case with atoms, `Y || H >> φ true [ext M]`. First, we can say confidently two of the postsuppositions:

1. `Y || H ctx`
2. `Y || H != φ type`

But what of `M`? One option would be the simplest, which is to say `Y || H != M in φ`. However, this does not seem to comport with Allen's supervaluation semantics, which allows the evidence to live in *any* model that has enough symbols (including ones that have more symbols!). So, this seems to suggest a slight change to the sequent judgment, to something like `Y || H >> φ true [ext ρ.M]`, postsupposing the following:

1. `Y || H ctx`
2. `Y || H != φ type`
3. There exists `Y'` such that `ρ : Y --> Y'`
4. `Y' || H.ρ != M in φ.ρ`

This allows us to generate new symbols in the course of knowing the truth of `φ`.

Question: Does this look like it should work? If we write up the usual rules for the proof theory, will they be sound according to these semantics? (i.e. will the postsuppositions hold?) I'm thinking it should work, since the renaming `ρ` will just percolate up the rule in the same way as the extracts—but there may be complications with renaming, since premises might become evident in mutually incompatible worlds, so we may need to rename things. 

@jozefg @freebroccolo @vrahli

**Comment by jozefg** [comment]
Should I read `rho.M` as `M` is a term in which `rho` is a substitution to which it may refer? If so then maybe 3 and 4 should be

 3. For every `Y'` so that we have a renaming `rho  : Y -> Y'`, then `Y' || H.rho != M in phi.rho`.

This I think solves the renaming issue because we have the freedom on the outside to pick `rho`. It also means that `M` must be sort of "stable" in the face of expansions because `rho` will tell it how to map the collection of symbols it uses into any larger, future domain no?

**Comment by jonsterling** [comment]
@jozefg By the clumsy notation `rho.M`, I just meant "a term `rho : Y -> Y'` is synthesized, along with a term `M` which lives at world `Y'`. The `rho` (and implicitly the particular `Y'`) was part of the synthesis of the judgment... I probably should have just written `<Y',rho, M>` or something

Because of the pervasive monotonicity property, `M` is automatically stable with respect to future worlds.

**Comment by jonsterling** [comment]
Oh, I think I see what you are getting at...

So, the synthesis would be `<Y', M>` such that `M` lives at `Y'`, and then on the outside we will choose a suitable `rho : Y -> Y'`. Is that your intention?

**Comment by jonsterling** [comment]
@jozefg If my above comment is kind of what you were thinking about, then I think that to make it work, it would end up being essentially equivalent to the original specification—that is, locally (within the subgoal) we must be confident that we have travelled into a world that is accessible from the main goal, so we will have to synthesize our own renaming anyway. And the main goal may choose a different renaming, just by composing some adjustment with the synthesized renaming. Does that makes sense, or have I missed something?
