### ISSUE TITLE
Emit elaboration progress in structured format

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-redprl#108]
1. Elaboration is done, and then the results are emitted
2. It would be nice to emit these results as we go
3. Right now, an elab'd signature can be emitted in JSON, but elaboration errors (such as incomplete proofs, etc.) are only formatted in "human readable(lol)" text. Would be very useful to have structured representation.

**Comment by jonsterling** [comment]
Getting closer! Elaboration now emits results incrementally. I do not yet have any structured representation of things yet, though.

**Comment by cangiuli** [comment]
Related: https://github.com/RedPRL/sml-redprl/issues/543
