### ISSUE TITLE
open head expansion rules

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-redprl#112]
- [x] open head expansion for equality
- [ ] head expansion for type equality
- [ ] can we do something analogous for truth? (hopefully?)

**Comment by cangiuli** [comment]
What do you mean by, something analogous for truth?

**Comment by jonsterling** [comment]
@cangiuli Something along the lines of "To show `H >> P true` when `H >> P => P'`, it suffices to show `H >> P' true`." (where `P => P'` is this restricted open computation judgment we've been kicking around—currently approximated only very conservatively)

**Comment by cangiuli** [comment]
As we discussed today, the current head expansion tactic should re-check the head operator for dimension name indices after each step.

**Comment by favonia** [comment]
I believe this thread is subsumed by #207 and also #230 about changing the machine.
