### ISSUE TITLE
add a "label" tactic

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-redprl#113]
This tactic should name a subgoal so that it can be picked visually out from the proof state easily.

**Comment by jonsterling** [comment]
To make this work, some fixes will have to be done to the (Dependent) LCF library, since metavariable names get killed by the unit to the monad... (The monad laws only hold up to alpha equivalence, I guess.)

**Comment by favonia** [comment]
Is this covered by RedPRL/sml-dependent-lcf#40?

**Comment by jonsterling** [comment]
@favonia I think it *may* be covered! It's hard for me to tell...

**Comment by favonia** [comment]
This should be trivial to finish now.
