### ISSUE TITLE
pretty print terms

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-redprl#115]

**Comment by ak3n** [comment]
Can you provide an example?

**Comment by jonsterling** [comment]
@ak3n Sure, I can try and explain what is going on and what the task is...

Currently, RedPRL terms are being printed every with `ShowAbt.toString`, so they come out in "abstract notation". In practice, this means unreadable stuff like `dfun(A; [x].B)`, where we really want it to be printed as `(x : A) -> B`. The correct notation for each term can be read off of the grammar `redprl.grm`.

In order to make this work properly with parenthesization & infix, etc., we should use the [unparser library](https://github.com/RedPRL/sml-unparse).

**Comment by jonsterling** [comment]
It would be cool to try and combine the above with the `wpp` library that I have imported, which deals with layout-related tasks (indentation, line breaks, line width, etc.) However, I don't yet know how to combine the two libraries (to get a combination of layout printing and fixity unparsing).

**Comment by ak3n** [comment]
Okay, thanks, I will try tomorrow.

**Comment by jonsterling** [comment]
@ak3n fantastic! Let me know if you have any other questions...

**Comment by ak3n** [comment]
As I understood I need to replace `PlainShowAbt` in [abt.sml](https://github.com/RedPRL/sml-redprl/blob/master/src/redprl/abt.sml).

Should I use [unparse_abt](https://github.com/RedPRL/sml-typed-abts/blob/master/src/unparser/unparse_abt.fun)?

**Comment by jonsterling** [comment]
@ak3n Yes, I think that a good start would be to replace use `UnparseAbt`; if I remember it correctly, the idea would be to write something like this:

```sml
structure UP = UnparseAbt (...)

fun notation m = 
  case Abt.out m of
     O.MONO O.DFUN $ [_ \ a, (_,[x]) \ bx] => SOME (* something here *)
   | _ => NONE

and unparse m =
  UP.unparse notation m
```

The idea is that the function `notation` above implements the custom printing that you desire, and the `unparse` function below it will wrap this such that the default/built-in printing is used for everything that you didn't specify. In `notation`, recursive calls should use `unparse`.

**Comment by ak3n** [comment]
Hm, what about `prettyDecl` which uses `ast`?

```ml
       | THM {arguments, params, goal, script} =>
           concat
             [kwd @@ text "Thm ",
              declId @@ text opid,
              text "(",
              text @@ argsToString (fn x => x) arguments,
              text ")", text " : ",
              squares @@ concat [nest 2 @@ concat [line, text @@ RedPrlAst.toString goal], line],
              text " by ",
              squares @@ concat [nest 2 @@ concat [line, text @@ RedPrlAst.toString script], line],
              text "."]
```

**Comment by jonsterling** [comment]
Hmmm... How about we don't worry about ASTs for now. If we get a pretty printer working for ABTs, I can later on rig it up to work on ASTs separately. 

--- jon

**Comment by jonsterling** [comment]
Thanks @ak3n for doing this! I'm going to close this ticket now, since the machinery is in place and working nicely. As we add more operators, we can augment the pretty printer as well.
