### ISSUE TITLE
Equality.Transitivity

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-redprl#119]
I'd like to support some kind of nice equational reasoning notation that doesn't require you to put in both sides of the equality at a priori. It seems like the right thing to do is rig up the transitivity rule such that it somehow only fixes one endpoint. Needs some design.

**Comment by jonsterling** [comment]
I'm designing most of the equational refinement rules to avoid the need for explicit transitivity reasoning—use of transitivity is kind of an artifact of natural-deduction style proof, and is not well-suited for refinement.

**Comment by favonia** [comment]
With #285 I guess this is considered done?

**Comment by jonsterling** [comment]
yes, that suffices!
