### ISSUE TITLE
Fun.Ext

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-redprl#126]
This will entail adding an extensionality mega-rule/tactic

**Comment by jonsterling** [comment]
[Note: in the case of equality of lambda terms, the basic equality rules are already sufficient; this would just be useful in more general cases. In any case, we could use eta expansion combined with lambda-equality to get general funext.]

**Comment by favonia** [comment]
Could you possibly provide an example in your mind that is not about lambdas? I guess some combination of these rules would be useful, but not sure of which one you are referring to.

**Comment by jonsterling** [comment]
@favonia The examples I had in mind were things like pair extensionality as well (if the projections are equal, then the whole things is equal)...

Ultimately, I figured I'd add these rules as soon as I needed them in a proof 😆

**Comment by favonia** [comment]
I think the current `auto` sort of already does this. So I guess you want a tactic that tries only these rules? In general I guess it's useful to have specific `auto`s and I feel we can easily code up one for "eta-expansion then equality".

**Comment by jonsterling** [comment]
@favonia Sure; though, the secret is I don't know that I have actually implemented these extensionality rules.

In any case, this issue is a low priority (I've updated it), so we shouldn't worry about it until it comes up in practice.
