### ISSUE TITLE
Σ types

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-redprl#131]
These can be added right away; probably not super interesting yet, because we don't have universes, but still worth doing.

**Comment by ak3n** [comment]
How? :)

**Comment by jonsterling** [comment]
There are several steps to adding Σ types:

- [ ] Add operators for `Σ(Α; [x].B)`, `<M,N>` and `fst(M)` and `snd(M)`, along with extensions to the parser and the pretty printer
- [ ] Add the computation rules of these operators to the RedPRL machine
- [ ] Add Kan compositions for sigma types, and the appropriate computation rules for `hcom` and `coe`
- [ ] Add refinement/sequent-calculus versions of the Σ-related rules from https://arxiv.org/abs/1606.09638 to the refiner
- [ ] Add development calculus operators for Σ (along with appropriate extensions to the parser), which should compute down to tactics in the machine

**Comment by ak3n** [comment]
@jonsterling thanks for the plan! It would be interesting to try. :D
