### ISSUE TITLE
Make Travis upload binaries to GitHub on tagged builds

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-redprl#132]
I don't know anything about compilers, but I assume that I would need to have Travis build separately for the major platforms...

**Comment by ak3n** [comment]
Also, I added a generated token as `api_key` to `RedPRL/sml-redprl` Travis's configuration.

Since now tagged commits should create a new release with an attached binary.

**Comment by jonsterling** [comment]
@ak3n I realized a couple things about this:

1. Is there a way to make this binary executable, without requiring the user to run `chmod` locally?
2. It would be nice if we could have Travis build this on multiple platforms; for instance, the binary produced probably only works on linux, but not on Mac OS.

**Comment by favonia** [comment]
@jonsterling I think we can put the file into a zip or something to have the correct permission. Also, Travis supports OS X builds.
