### ISSUE TITLE
Make dev calculus notation less bureaucratic

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-redprl#133]
It would be great to remove a lot of the braces, and just let the user use parens (or braces or something) to group code when necessary. This would have the side effect of making the code in the dev calculus seem less hierarchical, which would be nice.

**Comment by ak3n** [comment]
Make them optional in parser, but print with pretty printer?

**Comment by jonsterling** [comment]
@ak3n For now, don't worry about printing dev-calculus terms in the pretty printer; my main priority for the printer is that it be able to provide nice notations to things that will show up in proof goals (which won't include the dev calculus terms or tactics).
