### ISSUE TITLE
Add not[x] type (instance of univalence)?

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-redprl#137]
Might be worthwhile to add this type as an example of a non-trivial higher dimensional type.

**Comment by cangiuli** [comment]
You could add "isovalence" instead or in addition, although I am not sure whether there are enough rules implemented to actually prove that things are strict isomorphisms. As a stopgap measure, you could simply add a rule stating that `not` is a strict isomorphism.

**Comment by jonsterling** [comment]
@cangiuli I believe we can already prove that `not` is a strict isomorphism, but only for the strict booleans. I don't think we can prove it yet for weak bool, because we don't yet have any way to eliminate weak bool into an equality judgment.

**Comment by cangiuli** [comment]
That sounds right. I also plan to work on some low-hanging fruit (strict natural numbers, coproducts, etc.) this summer; those will provide much more fodder for strict univalence.

**Comment by jonsterling** [comment]
I'm going to close this ticket, since I prefer to just implement strict univalence.
