### ISSUE TITLE
Add basic testing infrastructure

### ISSUE THREAD

**Issue by wilcoxjay** [RedPRL/sml-redprl#151]
The main thing missing is the ability to assert that a certain development fails. While we're at it, we might as well support asserting that a certain development succeeds. 

There's no reason why these developments should be user-friendly or example-like.

**Comment by wilcoxjay** [comment]
Here's a proposed design:
* Add new subdirectories `test/success` and `test/failure`
* Extend `script/test.sh` to iterate over each file in these directories, asserting success or failure for each
* Refactor existing `test/test.prl` to split example-like things from regression tests. We can rename the example portion to, eg, `test/examples.prl`. Regression tests will be moved to `test/success`.

**Comment by jonsterling** [comment]
This sounds good! 👍

**Comment by wilcoxjay** [comment]
Closed by #154
