### ISSUE TITLE
Free metavars cause meaningless error message

### ISSUE THREAD

**Issue by wilcoxjay** [RedPRL/sml-redprl#153]
For example, change `#g` to `#h` in the definition of `cmp` in the [current `test.prl`](https://github.com/RedPRL/sml-redprl/blob/0b04b32b038b9cbb72ad17c7180af03be8bd12a5/test/test.prl). (And comment out `strictBoolTest` to work around #152.) You will get `Absent`  as an error message, with half-decent location information.

It would be nice if the error message was instead something like "Unbound metavariable 'h'".

The culprit is the [call to `lookup`](https://github.com/RedPRL/sml-typed-abts/blob/c90fc3895c7101516f833471905b3887267a4b9e/src/core/ast.fun#L113) in AST conversion in sml-typed-abts.

I think a quick fix would just be to handle exceptions from `lookup` there and report the name of the unbound metavariable.

**Comment by jonsterling** [comment]
Yes, I think the right approach is to handle this error in the conversion routine and report an error that can actually be acted on. Maybe that module should export some exceptions, from which the metavariable can be read—and then we can format an appropriate message in our signature elaborator.

**Comment by wilcoxjay** [comment]
Sounds good. Here's the design so far.

* Add `exception FreeMeta of string * annotation` to `AST_TO_ABT` 
* Handle the exception from `lookup` discussed above and throw `FreeMeta` instead

This will already be a big improvement without any changes in RedPRL, because the error message will have the words "meta" and the variable name. But the message won't be properly localized because the position information is thrown as part of the exception, rather than being known by the calling environment. I'm not sure what to do about that.

**Comment by jonsterling** [comment]
@wilcoxjay OK, this sounds reasonable. If you make the change you suggest, I may be able to help figure out how to get the position info in the right place.

**Comment by wilcoxjay** [comment]
Okay, I made the changes discussed above. 

Unfortunately, without changing RedPRL yet, the error message is not as good as I expected. It just prints "FreeMeta" even though the metavariable name is in there somewhere.

@jonsterling What's the right way to format this kind of thing?

**Comment by jonsterling** [comment]
@wilcoxjay Yeah, if the exception just bubbles to the top level, ML will only print the constructor name. What you need to do is handle this error specifically at the call-site (in the elaborator I guess), and format it by extracting the metavariable from the exception, and turning the metavariable into a string (using `Metavar.toString` or whatever).

**Comment by jonsterling** [comment]
(For now you could just use `raise Fail "the formatted error message"` if it is not clear how to integrate this properly with RedPRL's error reporting mechanism, and we could clean it up later. Or you could have a go at doing it all the way, if it seems possible.)

**Comment by wilcoxjay** [comment]
Okay, I tried to use RedPRL's error reporting stuff.

I handle `FreeMeta` in the elaborator and raise a RedPRL error with proper position information. 

In the process of testing, I noticed that the elaborator monad actually ignores position annotations when formatting exceptions. So I submitted an additional PR (#157) to fix that.

The build of #155 is broken until RedPRL/sml-typed-abts#77 is merged. @jonsterling could you review that PR when you have a chance and let me know if it's okay to merge?

Finally, I also noticed that the recent changed to `test.sh` completely silenced any errors from MLton, so I submitted yet another PR (#156) to address this.

**Comment by wilcoxjay** [comment]
Closed via #155.
