### ISSUE TITLE
Unused variables in various binders

### ISSUE THREAD

**Issue by wilcoxjay** [RedPRL/sml-redprl#163]
It would be nice if RedPRL supported various common notations for unused bound variables. 

As a first cut, allowing `_` to be used in binding position to signify that the bound variable will not be used.

Even better, some syntactic forms have well known shorthand notations for the case where the bound variable is not used. For example, `A -> B` instead of `(_ : A) -> B`.

**Comment by wilcoxjay** [comment]
#164 addresses the second part of this, modulo parser ambiguity.

For the first part, is anyone opposed to supporting a general `_` notation for unused binders?

**Comment by wilcoxjay** [comment]
I've updated #164 with prototype support for `_` as an unused binder.

**Comment by jonsterling** [comment]
@wilcoxjay `_` makes sense for this purpose
