### ISSUE TITLE
Fix parser conflicts

### ISSUE THREAD

**Issue by wilcoxjay** [RedPRL/sml-redprl#166]
The RedPRL parser currently reports a large number of shift/reduce and reduce/reduce conflicts. 

Here is my limited understanding of the classes of conflicts:
* mlyacc resolves shift/reduce conflicts by reporting the conflict and then choosing the shift. These are usually relatively easy to fix by adding precedence or associativity annotations. 
* mlyacc resolves reduce/reduce conflicts by reporting the conflict and then choosing the rule that appears earlier in the grammar file. These usually indicate some kind of "real" ambiguity in the grammar and may require some actual decision to be made.

The only remaining conflict to fix is:
- [x] between custom operators and grouping parentheses, described [here](https://github.com/RedPRL/sml-redprl/blob/76cb4750f9d7be063ca4aad37be940bebd5cf782/test/success/conflict.prl#L1-L5).

**Comment by wilcoxjay** [comment]
I fixed most of the conflicts in PR #167. There were a few worth noting here, and there's one main one left.

* The one remaining cause of error is an ambiguity between custom operators and using parentheses for grouping. See theorem `custom-op-versus-parens` in `test/success/conflict.prl`. (Note that `conflict.prl` is intentionally marked as "succeeding" despite failing currently. It will succeed once we resolve the conflict.)

* There are two ways to convert a multitactic to a tactic:
    * Via <| |>, which is not currently used anywhere in the test suite
    * Implicitly, via the `rawTactic` rule, which is used extensively

   Was the implicit conversion intended to be used so pervasively? If so, is there any reason to keep the <| |> construction?

* The empty string is parsed as the identity tactic, which causes ambiguity in various places. For example, in a multitactic context, `[]` could conceivabily be parsed as the "empty" `each` mtac, or the singleton `each` mtac, with `id` as its only element. The parser currently chooses the latter, but its not clear that it should. This results in a "rule not reduced warning", because the parser never needs to produce the empty list of tactics.

* Identifiers are valid tactics, but I can't figure out what for (no uses in test suite). This causes a shift/reduce conflict with hypBindings. For now, I've resolved it by deleting the rule that parses IDENTs as tactics.

**Comment by wilcoxjay** [comment]
I should also note that I was perhaps a bit too hasty with some of these changes -- I didn't stop to carefully test the behavior before and after. So, especially for constructs that weren't used anywhere, I may have broken something.

**Comment by jonsterling** [comment]
1. the `<|...|>` thing is important in some cases—I haven't documented it since I'm still understanding how this tactic system works, but to summarize, this allows you to force a depth-first application of a tactic in a multitactical. I will try to explain this better... It is at least touched upon in my upcoming paper.

2. the thing in `rawTactic` looks suspicious, but let's leave it in for now. I will have a look at fiddling with it soon, and maybe finding a way to remove it.

**Comment by wilcoxjay** [comment]
Closed by #167
