### ISSUE TITLE
Should '@' be allowed as a character in identifiers?

### ISSUE THREAD

**Issue by wilcoxjay** [RedPRL/sml-redprl#169]
It is currently allowed in the lexer.

IMO, it would be convenient if it were *disallowed* since then one could write things like `f x@i` instead of `f x @ i` or `f x @i` to idiomatically emphasize that `@` as an operator binds tighter than function application, working around the fact that parens are currently not allowed around arguments to functions.

**Comment by jonsterling** [comment]
I think it should not be allowed; probably the only reason it's in there is I copied and pasted the beginning of the lexer from something else (lol!).
