### ISSUE TITLE
Add discussion of theoretical basis

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-redprl#17]
In the *Definition*, we should cite and briefly summarize both *Syntax and Semantics of Abstract Binding Trees* and *Type Refinements for the Working Class*.

**Comment by markfarrell** [comment]
I think the category-theoretic parts of _Syntax and Semantics of Abstract Binding Trees_ and _Type Refinements for the Working Class_ are giving me the most trouble, at the moment. For example, in _Syntax and Semantics of Abstract Binding Trees_, I am lost beyond the fact that it is possible to interpret contexts into a category with objects as contexts and e.g. renaming of symbol as morphisms (or, e.g. substitutions in the case of variable contexts, if I understand correctly). This is mostly me though, and I think I need to get up to speed if I also want to e.g. understand the semantics of the cubical type theory paper, on a related note, as well.

Anyways, I suppose my question is: should/will the _Definition of Red JonPRL_ be _uncategorized_ completely?

Also, maybe illustrating and extending your examples in _Syntax and Semantics of Abstract Binding Trees_, i.e. the lambda calculus and assignable references calculus examples, in code, would be useful in the definition?

**Comment by markfarrell** [comment]
An additional thought:

What is an example of properties I could prove about programs in Red JonPRL that I couldn't elsewhere? For example, in theory, would I be able to prove that e.g. selection sort and merge sort formulated in ALGOL 60 (having both expressions and commands) are extensionally equal in Red JonPRL? What would the prospects of doing this in Red JonPRL, as opposed to elsewhere?

**Comment by markfarrell** [comment]
I really like these paragraphs, by the way, as a starting point:

![screenshot-github com 2016-02-07 11-50-58](https://cloud.githubusercontent.com/assets/2190984/12872989/1f6abb1a-cdaa-11e5-86a2-29951cc8f362.png)

![screenshot-github com 2016-02-07 11-51-23](https://cloud.githubusercontent.com/assets/2190984/12872994/357e34e0-cdaa-11e5-95ca-16fecf1fd27c.png)

**Comment by jonsterling** [comment]
Hi Mark,

I will respond in more detail later, but to address the category theory question--- the reason for the categorical treatment in both cases is that the machinery is very elaborate and categorical language allows us to "factor out" a lot of complexity. In the ABTs paper, you can safely ignore all the scary sheaf stuff---there is a technical reason why we need it, but it is not really the essence of what is going on here. For your purposes, the sheaf stuff (which exists to ensure that strengthening holds for symbols) as well as the entire section on the categorical semantics can probably be ignored.

However, if you look at the Refinements paper, it is already mostly "uncategorified" (for instance, in the rules, rather than working internally to the topos, we work externally and quantify over renamings etc.); we chose to do this because we didn't want to give the impression that there was something essentially categorical about our meaning explanation. In other places in the paper, though (such as the explanation of types as computation-respecting refinements), it was more convenient to use categorical language. 

It would be a good idea for us to add some more detailed example of a language to the ABT paper, such as an appendix developing Harper's Modernized Algol.

Best,
Jon

**Comment by jonsterling** [comment]
I will respond in more detail later, but to address the category theory question--- the reason for the categorical treatment in both cases is that the machinery is very elaborate and categorical language allows us to "factor out" a lot of complexity. In the ABTs paper, you can safely ignore all the scary sheaf stuff---there is a technical reason why we need it, but it is not really the essence of what is going on here. For your purposes, the sheaf stuff (which exists to ensure that strengthening holds for symbols) as well as the entire section on the categorical semantics can probably be ignored.

However, if you look at the Refinements paper, it is already mostly "uncategorified" (for instance, in the rules, rather than working internally to the topos, we work externally and quantify over renamings etc.); we chose to do this because we didn't want to give the impression that there was something essentially categorical about our meaning explanation. In other places in the paper, though (such as the explanation of types as computation-respecting refinements), it was more convenient to use categorical language.

It would be a good idea for us to add some more detailed example of a language to the ABT paper, such as an appendix developing Harper's Modernized Algol.

Best,
Jon

**Comment by jonsterling** [comment]
Red JonPRL's syntactic framework makes it plausible that we could define the syntax of the states of an ALGOL machine as then impose an operational semantics on them—and then we could use our refiner to reason about the computation of ALGOL procedures. There are not currently any plans to do this, but it would be an interesting project!

**Comment by jonsterling** [comment]
> What is an example of properties I could prove about programs in Red JonPRL that I couldn't elsewhere? 

So, in comparison to Coq, you can prove theorems about computational and extensional equivalence of programs, and then *use these* theorems to justify rewriting some other goal. In Coq, you can prove extensional equivalence of programs, but it's not that useful because you can't do anything with the proof afterward; and you can't prove computational equivalence because there's no way to talk about computation in Coq.

What you *can* do in Coq is formalize the operational semantics of a programming language and then formalize a type system, and define computational equivalence and show that your little type system respects it, etc. In Coq, when you do this, you're doing metamathematics; JonPRL and Nuprl are a lot stronger in this area, because rather than the user defining a little closed language and then defining computation for it, you're actually observing the computation of JonPRL's programming language itself, and all of JonPRL's type theory is arranged such that it respects this notion of computation.

Here's an example of something you can prove in Nuprl, that you can't prove in Coq:

> Every stream processor is "merely" continuous. (Where by "merely", I mean that we can calculate its modulus of continuity, but we cannot do so continuously.) Furthermore, you can also prove Brouwer's Fan Theorem, from which you can show that all functions on the reals are *uniformly* continuous.

We're intending to make it possible to prove these things as well in Red JonPRL. It relies on two things that Coq probably can't have (except perhaps through some kind of forcing layer, like what Sozeau was working on):

1. Exceptions with fresh exception names (which will be very elegant thanks to the ABT framework).
2. The Bar Principle—an intuitionistic principle that states that a proof like `forall (X : stream(Nat)), exists n : Nat, P(X[n])` can always be analyzed into a wellordered tree. We can add this consistently because it is possible to give evidence for membership that it separate from the object under consideration.

Using exceptions you can prove that everything in sight is continuous. Using the Bar Principle, you can prove its special case called the Fan Theorem (the Fan Theorem is basically the Bar Theorem when restricted to streams of `0,1`-bits instead of streams of natural numbers); using the Fan Theorem, we can prove that every continuous real function is uniformly continuous.

**Comment by jonsterling** [comment]
@markfarrell The other thing we intend to do, longer term, is add mutable references to JonPRL. It's not yet totally clear how to integrate higher order state with CTT, but it seems like it will be possible. I'm excited about this, because you'll be able to use JonPRL to prove behavioral specifications of imperative programs! (if and when we add this).

What we might do for now is start with first order mutable references (such as references that can only hold integers or something); it seems like it should be pretty clear how to get that working much sooner than we have a treatment of general references.

Conceivably, mutable state could also be added to Coq using forcing, but it's a long way off.
