### ISSUE TITLE
Support sequents in the frontend

### ISSUE THREAD

**Issue by wilcoxjay** [RedPRL/sml-redprl#176]
All of RedPRL's internals manipulate sequents, but there is no way for a user to give a nontrivial sequent explicitly. It would be nice if there was such a way.

For example, this would let you prove "polymorphic theorems", which would traditionally be stated by quantifying over a universe, by instead stating, eg, `A type >> A -> A true`.

There are some things to be worked out:
* Represent sequents in the abstract syntax; there are some tricky issues with the binding structure of sequents. (@jonsterling could you expand on what you meant here?)
* Represent sequents in the concrete syntax. This should be fairly straightforward once we figure out the abstract counterpart. I'm happy to do the requisite parser hacking.
* Generalize the elaborator's implementation of the `Thm` command to tolerate nontrivial sequents, if necessary.
* Generalize the Lemma rule to nontrivial sequents, if necessary.
* Think carefully about the well formedness invariants required by the proof theory and ensure that these are checked on "untrusted" sequents.

**Comment by jonsterling** [comment]
Thanks for opening this ticket! Here are some remarks about the binding structure of sequents:

A sequent consists in a telescope and a conclusion. The names bound in the telescope need to get bound in the conclusion, which leads to a bit of a strange underlying structure; for instance, the sequent `a : A, b : B[a] >> C[a,b]` is has to be structured something like `cons(A; [a].cons(B; [b]. concl(C[a,b]))`. Also, recall that the sort of the variables bound in the sequent corresponds to the sort of object that is to be constructed by the judgment. One way to formulate it I guess is to have operators with the following arities:

```
seq-concl : ([].jdg)seq
seq-cons{τ} : ([].jdg; [τ].seq)seq
```

Then, for well-formedness, we would need to check the following invariant:

Each judgment in the context of a sequent (that is, each first argument to `seq-cons{τ}`) must be interpretable as a categorical judgment (see the abt conversions in `RedPrlCategoricalJudgment`), and its synthesis/evidence sort must be equal to `τ`.
