### ISSUE TITLE
Implement HCom.True, FCom.True, Com.True and Coe.True.

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-redprl#184]
Right now we have only equality rules for primitive hcom terms. It would be nice to think about Kan compositions from the perspective of proof refinement, however—i.e. focusing on the judgment `A true` rather than `M = N in A`.

This would allow us to get *interactive* programming of compositions, which is essential—for instance, you can watch the coherence goals change as you adjust part of the composition problem, etc.

Additionally, maybe there is some way that the refinement perspective can help us make the goals simpler. (Not sure about this, but it often happens to be the case when switching from membership to truth, especially when you have dependent refinement.)

@cangiuli

**Comment by cangiuli** [comment]
Well, the purpose of `hcom` is essentially to inhabit various path types, while the goal of `coe` is to inhabit a type when you have already inhabited some similar type.

**Comment by jonsterling** [comment]
I agree with all this

The idea is that every form of untyped construction should have a "refinement" version which elaborates to a tactic script; this lets you put holes in programs and develop them interactively with feedback from the refiner (or delegate some portion of the construction to a general purpose tactic).

So, I think that both hcom and coe can benefit from this treatment—and even more so if we spend a bit of time designing refinement rules for them with ergonomics in mind.

**Comment by favonia** [comment]
So, this is essentially a rule taking a direction and maybe a list of equations?

**Comment by jonsterling** [comment]
@favonia Yes, something along those lines... Though it may be possible to design something even more "refinement"-style, not sure.

**Comment by favonia** [comment]
Hmm I am not sure how `Coe.True` should work automatically. I think we need something like `DEV_COE`.

**Comment by jonsterling** [comment]
@favonia The idea is that we would have a primitive rule for constructing COEs by refinement, and `DEV_COE` would call this rule; but `DEV_COE` is a separate consideration.

When I get better, I can start designing these refinement rules.

**Comment by favonia** [comment]
The problem is that the rule needs the user to decide the starting and ending dimension expressions, and we don't have a goal for users to fill in dimension expressions (yet). Anyways I will leave it to you.

**Comment by jonsterling** [comment]
@favonia I would regard those things are parameters to the rule; anyway, we can figure it out later...

**Comment by favonia** [comment]
@jonsterling Please correct it if I misunderstood your intention.

**Comment by favonia** [comment]
Time to rethink about these as dimensions have become expressions.
