### ISSUE TITLE
Implement strict univalence

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-redprl#189]

**Comment by favonia** [comment]
Is this isovalence in Carlo's documents?

**Comment by jonsterling** [comment]
@favonia Carlo used to use the term "isovalence", but in his documents, it is called "isomorphism-univalence".

**Comment by favonia** [comment]
@jonsterling Thanks. To clarify, I do not really care about the names. Just to make sure I understand what it is.

**Comment by cangiuli** [comment]
To be honest, I haven't decided what the official name is.

**Comment by favonia** [comment]
Closed as being subsumed by the ultimate V types.
