### ISSUE TITLE
Remove type_tag and redesign hcom in the stack machine semantics

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#192]
Currently `type_tag` is used to represent (the head symbol of) a value type and determine the behavior of the hcom being indexed, but one can skip these intermediate steps and directly dispatch on the value types in focus. After this optimization, `type_tag` can be completely removed. Note that we might need a separate hcom for base types where hcom's may be regarded as values.

**Comment by jonsterling** [comment]
@favonia I have been thinking about this, and what can actually be done at this time is not so exciting. Here is the best that can be done:

We can add a special hcom for base types, but it will not necessarily be a value. It is a value if its extents all variables, and if `r,r'` are distinct. But this hcom will still need `type_tag`—in the operational semantics it is not necessary to know what type the hcom is from at this point, but if one of these base type hcoms shows up in a typing judgment, we would need to know the type. It would be possible to get around this by adding special cased typing rules for value hcoms in `bool` and in `S1`, but I would like to avoid this duplication.

What this means it that `type_tag` can be removed from "general hcoms" (the ones where the type is not yet resolved/computed), but that `type_tag` would have to be kept for base type hcoms. The only difference is that there would be no `TAG_NONE`.

All in all, these changes sound very superficial and unlikely to result in any conceptual improvement. I would suggest that we defer making any such changes until we can remove the `type_tag` ENTIRELY.

**Comment by favonia** [comment]
@jonsterling In light of #207 I feel the separation may be useful.

**Comment by favonia** [comment]
@jonsterling Related to this issue, is it possible to allow the atomic hcom stepper to return a new value after the substitution is (partially) forced? For the new hcom in #206, I expect that equations of hcom values in base types will have lots of 0 and 1. And if they are forced during the checking, I think we should keep the resolved values to save time in further checking.

**Comment by jonsterling** [comment]
@favonia 

> In light of #207 I feel the separation may be useful

Maybe, but it seems like we could just as well implement #207 in the way you suggest, and then branch on the existing tags. I'm not totally opposed to what you say here, but I'd like to make sure that it doesn't cause a blow-up of code & bureaucracy.

>  Related to this issue, is it possible to allow the atomic hcom stepper to return a new value after the substitution is (partially) forced?

This sounds interesting, but I don't think I understand what you mean yet. Could you explain it to me in a little more detail?

**Comment by favonia** [comment]
@jonsterling I believe it just means killing all non-base tags and move all the code for non-base types to `cut`. I have to try to see whit this really means though.

Right now, when I do `safeEval`, all the equations might have to be checked. If during the process something is resolved to, say, `APP DIM0`, I do not want to redo the work next time.

**Comment by jonsterling** [comment]
I don't think I understand, but let's talk about it in person instead so you can walk me through what you mean.
