### ISSUE TITLE
Rename ID types to PATH types.

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#193]
Due to various concerns I think paths are a better name for the current ID types in RedPRL. I can do the renaming if there is no objection.

**Comment by jonsterling** [comment]
Good idea, agreed.

**Comment by favonia** [comment]
@jonsterling It seems there is not enough testing for ID types, because my changes did not break anything! Well, I kind of expected this because it is not mentioned in the lexer. I am not sure if I can close this thread if it was not properly tested.

**Comment by jonsterling** [comment]
We don't worry too much about thorough testing in RedPRL, given our lack of engineering power. It's too hard to test a proof assistant in a thorough way, especially one that is constantly changing. Instead, we just make sure some basic examples continue to work.
