### ISSUE TITLE
Replace toString by pretty everywhere

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#200]
Currently, `Signature` is unable to print out `ast jdg` and other things. A radical but complete solution is to implement `toString` by `pretty` everywhere.

**Comment by favonia** [comment]
I updated the description after talking to @jonsterling. Now we have clear goals and know what to do.

**Comment by favonia** [comment]
@jonsterling It turns out I also have to update other libraries which RedPRL depends on. For example, I have to update the signature `LCF_BINDING_JUDGMENT` in RedPRL/sml-dependent-lcf.

**Comment by jonsterling** [comment]
@favonia Let's not do that just yet.

**Comment by jonsterling** [comment]
@favonia In fact, as discussed, let's hold off on addressing this until the new pretty printing library is available.

**Comment by jonsterling** [comment]
This will be *mostly* addressed by #238; I will tackle the remaining cases (in the error reporting apparatus) soon.
