### ISSUE TITLE
`safeEval` is too conservative and inefficient

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#207]
@cangiuli @jonsterling `safeEval` seems way too conservative and inefficient to me. Ideas:

It seems we only have to check whether it is hcom and coe in base types. All other rules are either safe (independent of dim) or safety-preserving (which should already be an operator on the stack, except some hcom/coe holding non-base tags until issue #192 is resolved). Therefore, we should not force the delayed substitution unless it is critical for us to determine safety, and should bravely step in all other cases.

Forgot to say that, even in base types, the cap rule should fire whenever possible.

Related discussion is in #175.

**Comment by jonsterling** [comment]
I would be delighted if we could do something less draconian than checking for free dimension variables in the head. Discussion with @cangiuli made me think that we could not afford to be that much less conservative, but maybe it is possible.

I'll leave it up to @cangiuli.

**Comment by favonia** [comment]
Maybe I misunderstood the safety criterion here. I was assuming that a step M ↦ N is safe if and only if for any dimension substitution φ, Mφ ↦ Nφ. Or, "cubically stable".

**Comment by jonsterling** [comment]
> Maybe I misunderstood the safety criterion here. I was assuming that a step M ↦ N is safe if and only if for any dimension substitution φ, Mφ ↦ Nφ. Or, "cubically stable".

We'd have to check with Carlo to be sure, but even assuming this is the only condition we need, then your initial statement ("all other rules are either safe or safety-preserving") would not be true; consider the example of `loop{x}`, whose computation is *not* stable under cube maps in this sense. (We resort to an *equational* "computation" rule in cases like this.)

**Comment by jozefg** [comment]
I lol'ed at seeing an issue on redprl mention efficiency.

**Comment by jonsterling** [comment]
@jozefg We should just switch to C++ and it will become automatically efficient.

**Comment by favonia** [comment]
@jonsterling It is okay, because `loop{x}` is not and will not be stepping into anything in `safeStep`. In general, if something is pretended to be a value and we do nothing, it is okay, as long as we do not declare `S.Val`.

**Comment by jonsterling** [comment]
@favonia That's a good point. Let's discuss it with Carlo, and maybe we can design a more well-thought-out "open computation judgment" which is cubically stable.

**Comment by favonia** [comment]
@jozefg You should ask Guy about an encouraging story and also recognize the Cubical Thought.
