### ISSUE TITLE
New style of refinement logic

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-redprl#208]
I've been theorizing a new way to arrange PRLs which can lead to a big decrease in the number of necessary rules. Currently, there is a conceptual duplication of rules for inhabitation (which produce a program as extract), and rules for equality (which produce a trivial extract).

One way to resolve the contradiction is to start from a judgment of "twin inhabitation", which produces two extracts which are equal to each other in the appropriate type. Then, the equality judgment can be introduced uniformly using the inhabitation judgment and a syntactic equality judgment: to show that `e1,e2` are equal elements of type `A`, show that inhabit `A` is inhabited such that the twin extracts are exactly `e1,e1`.

Then, all the structural equality rules become derivable.

The only obstacle to doing this in RedPRL is that our refinement apparatus doesn't support multiple outputs / extracts; however, we can work around this by having a sort for "twin elements" and auxiliary judgments to project these elements. Using some helper functions, the refiner can be written without being too bureaucratic.

**Comment by favonia** [comment]
Question: does the potential optimization I want to do in #206 which produces `MEM` when possible will be unnecessary in the new style?

**Comment by jonsterling** [comment]
@favonia I'm not really sure what you're referring to.

**Comment by favonia** [comment]
I was thinking that, when proving that a hcom is in some type (the unary version), maybe some of the goals can be of the unary version (membership) instead of the binary version, but then realized maybe a solution to this issue (#208) will make this kind of optimizations useless.

**Comment by jonsterling** [comment]
@favonia I see! It's worth noting that membership vs equality is only an optimization at the level of *writing* the code of the refiner, since membership is actually nothing more than a notation for equality—to prove membership, you must prove equality.
