### ISSUE TITLE
user-defined canonical operators & computation rules

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-redprl#23]
Supporting this would be awesome! If we added PER types, then users could really treat Red JonPRL like a fully open-ended logical framework.

It would be nice, however, to ensure that the computational properties of the theory are not destroyed by a bad definition. For instance, it would be nice to support some syntactic check that approximates the extensionality condition for operators; there ought to be some removable subset of definitions that we can accept which are always extensional, I would think. We would also want to ensure that the definitions preserve determinism.

**Comment by jonsterling** [comment]
One option that would be extremely cool is to provide a way to *prove* that an operator is extensional within JonPRL; then, we could elaborate computation rule definitions to also include a proof obligation.

@jozefg the extensionality condition be expressed perspicuously *inside* of CTT?

**Comment by jozefg** [comment]
Hm.. I'd need to think of this more carefully to be sure but I would be surprised if it could be. You need to be able to inspect a derivation of a program stepping to a value and having access to the computation system like this *from inside the computation system* seems dangerous.. I'm also not sure that these proofs are completely stable under arbitrary additions to the system so bad things might happen if I prove on extensionality proof, you add another operator which is extensional, but somehow this breaks the extensionality of my operator. Perhaps the condition could be approximated by requiring to extensionality proof to be uniform in the derivation of the evaluation of the program. Then we could I suppose just hand them the hypotheses the the program is ceq to a result and tell them to go from there.

**Comment by jonsterling** [comment]
@jozefg Yeah, it sounds a bit tricky... If extensionality proofs are not modular, this is rather concerning on its own. Perhaps @vrahli can comment?
