### ISSUE TITLE
Serious attention to rules for lemmas, assertions, etc.

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-redprl#242]
These are so bad right now! I want to implement this properly, and add support for backward chaining, etc. I'll work on this very soon, since it's going to absolutely crucial for using RedPRL in practice.

**Comment by jonsterling** [comment]
I want to start taking this on, hopefully to be resolved at least partly this week.

**Comment by jonsterling** [comment]
Assertions should induce another hypothesis that says that the assumption is equal to the thing that we construct. This will help with @favonia's question that we discussed over email, in conjunction with #259.

**Comment by favonia** [comment]
What exactly are we trying to achieve in this issue? Have we done except for maybe backward chaining?

**Comment by jonsterling** [comment]
I have made some progress (mostly be deleting stuff that didn't work well); there's more to do, and I'd like to keep this open to track it, even if the task is kind of nebulous.

Basically, the ergonomics (or lack thereof) of what we have can only be determined through practice, and without a universe, opportunities for testing these facilities in practice are very rare. So, expect the concrete demands of this ticket to be sharpened as other parts of redprl (like universes) become developed.

**Comment by jonsterling** [comment]
I'm closing this in light of #299; I will open a new ticket for backward chaining.
