### ISSUE TITLE
Move various "rules" out of `refiner.fun`.

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#245]
(This may be related to #242.)

I have some lingering questions:
- Should we move all the `AutoEq` out of individual type-specific modules?
- When one finished proving `EQ ((m, n), ty)`, can we assume `ty` is a type? This is true on paper and in modals.

**Comment by jonsterling** [comment]
@favonia Great questions!

1. I would like to eventually enforce a strict separation of tactics from rules. Things like `Auto...` are tactics, and everything which consructs its own extract term is a rule. The tactics could live in another module, perhaps functorized over the refiner signature.

2. Yes, this is correct.

**Comment by favonia** [comment]
@jonsterling I think it is difficult to make it a functor because the `Auto` tactic needs to know exactly what the canonical forms and other things are.

**Comment by favonia** [comment]
@jonsterling I realized that testing alpha equivalence before generating certain subgoals might violate the definition of "rule" in your paper. If so, many rules were "polluted" and are tactics at best.

**Comment by jonsterling** [comment]
@favonia I was wondering about that too... It goes back to what I originally said, which is the rules should not be doing clever things, and that discharging trivial stuff ought to be done with tactics. This is not as efficient, of course, but it is cleaner.

However, I'm fine with leaving your clever equality checks in for now, unless it leads to a problem in practice. Eventually we may want to remove it.

**Comment by favonia** [comment]
@jonsterling On the other hand, could you relax the lax naturality even further? (superlax?) That is, if it's a subtelescope it's still okay or something. Then I can claim they are still rules.

**Comment by jonsterling** [comment]
Maybe we could think of a way to relax the definition to regard these as rules, but ultimately I think the semantic constraint is our friend. I did some thinking, and I feel that branching like this will likely make automation and tactic-writing more difficult in the future, since it makes it harder to predict the shape of subgoals. 

I think ultimately we may want to remove these things, or if we left them in, we could just consider them an implementation hack that is done for the sake of performance, which is probably ok too.

**Comment by favonia** [comment]
A compromise could be having a trivial goal. With this, the shape is the same, but any goal could be trivial. I guess anything excluding the permanent-failure is an approximation of the trivial goal? The auto tactic can clear up all the trivial goals.

**Comment by favonia** [comment]
For the source files, should we rename `refiner*` to `rules` and then create another one named `tactics`?

**Comment by jonsterling** [comment]
@favonia We could do this, certainly. If you need to do it in order to make progress on something else, let's do it now. Otherwise, I'd like to focus on the core tasks that we have to undertake for making RedPRL useful, and avoid getting buried under yak shaving -type tasks.

**Comment by favonia** [comment]
Now that we have a separate tactic elaborator, what could be the technical difficulty if we want to move Auto into the tactic elaborator? Or maybe this would be trivial when we have a good metalanguage?

**Comment by jonsterling** [comment]
@favonia That's a good idea; we should probably do so eventually, but I'd like to hold off on making those kinds of cosmetic changes unless they are necessary in order to achieve something else.

**Comment by favonia** [comment]
A note to myself: move various rules in `Synth` back to `refiner_types.fun`.
