### ISSUE TITLE
Documentation on the spec of refining rules

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#248]
Specification of the telescopes and the categorical judgments that every rule needs to follow:

- Telescopes
    - An `EQ ((m,n),ty)` in the context implies `TYPE ty`.

- Goals to prove:
    - All new goals assume nothing. For example, while proving `EQ ((m,n),ty)` it is not known that `TYPE ty`.

- Satisfied goals:
    - A satisfied `EQ ((m,n),ty)` goal implies `TYPE ty`.
    - A satisfied `TRUE ty` goal with the hole `m` implies `TYPE ty` and `MEM (m, ty)`.
    - A satisfied `SYNTH ty` with the hole `m` goal implies `TYPE ty` and `MEM (m, ty)`.

By the way, a `SYNTH` for `if/s` can be done by `if/s` itself, but the generated type may not be what the user want.

(This issue will be closed once the documentation is completed.)

**Comment by favonia** [comment]
@jonsterling Is this correct? By the way, there should be a label for documentation.

**Comment by jonsterling** [comment]
thank you for opening this! i will review it once I have defeated my jet-lag, and then we can incorporate it as documentation!

**Comment by jonsterling** [comment]
@favonia Just reviewed your notes here, and it all looks correct. good!
