### ISSUE TITLE
reflect refiner into the computation system

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-redprl#25]
So, currently theorem declarations are elaborated into definitions like `mythm = prove(goal; script)`. Initially, I was just thinking this was a convenient way to store the data of the proposed proof as an abt, but now I am thinking it would be _extremely_ cool to actually reflect the behavior of the refiner into the computation system, such that `prove(goal; script)` actually computes to a term that codes up the result of refining the goal with that script.

Then, the action of the "proof checking" elaborator phase would be to evaluate all such declarations, and ensure that they result in so subgoals. So, `prove` would be sort of an oracle, from that standpoint.

**Comment by jonsterling** [comment]
[I should note, this is just an idea that occurred to me—I do not have direct plans to implement it, because I do not know if it is a valid extension of the computation system.]

**Comment by jonsterling** [comment]
I have thought about it a little bit, and I'm more confident that this can be done safely. However, it would require restructuring things a bit, since the refiner and the operational semantics would have to be defined in mutual recursion.

**Comment by jonsterling** [comment]
I think it's essentially what @david-christiansen tried to convince me of a few months ago; I don't think I understood at that time how cool this could be.

**Comment by david-christiansen** [comment]
I'll make a Lisper out of you yet :-)

**Comment by david-christiansen** [comment]
Have you seen Eli Barzilay's PhD thesis?

**Comment by jonsterling** [comment]
@david-christiansen I did, but I need to read it again...

**Comment by favonia** [comment]
I wonder about the current state of this issue. If I understand this idea correctly, should the final result be the same as pretending there is a "?" at the end of the script and then encoding the output?

**Comment by jonsterling** [comment]
I'm going to close this ticket since, while I think it's really cool, I think it doesn't fit in the long-term design plan for RedPRL.
