### ISSUE TITLE
Pattern matching for inductive types?

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#263]
I wonder to what degree this can be done (without changing the refinement framework too much)?

**Comment by jonsterling** [comment]
This one is fairly unlikely... It would be nice, but I can say with some confidence that we would never achieve something as nice as Agda or Idris-style pattern matching.

There may be a possibility of writing some very fancy tactics à la Conor McBride's thesis, but I would guess it is not super likely.

**Comment by jonsterling** [comment]
I'll note here that I have added pattern decomposition for records a week or so ago; but I don't know what can be done about pattern matching for (higher) inductive types yet.

**Comment by favonia** [comment]
For historical records, the decomposition patterns for single-constructor types were done in #298.
