### ISSUE TITLE
Paramater sort checking

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#264]
This should be rejected, because `i` is of the wrong sort. However, it seems that the current parameter sort checking is not taking a parameter context...?
```
Thm Cap{i : exn}(#A) : [ 
  a/type : #A type,
  x : #A
  >> (hcom{0 ~> 0} #A x [i=0 {_} x] [i=1 {_} x]) = x in #A
] by [
  auto
].
```

**Comment by favonia** [comment]
I wonder if we should have a "bug" label.

**Comment by jonsterling** [comment]
Probably some checks got left out of the elaborator; this in particular should be checked by calculating the support of the term, and checking with `i` is included in that support, and if so, whether it has the right sort.

**Comment by favonia** [comment]
Hmm not sure how to fix this without changing the abt library. Maybe there is some API I missed.

**Comment by jonsterling** [comment]
@favonia Please don't worry about this for now; I can fix it once I get better.
