### ISSUE TITLE
A tactic to call SMT solvers.

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#269]
Certainly doable by, for example, translating Z3 proof rules into RedPRL scripts.

**Comment by gabriel-fallen** [comment]
@favonia do you mean other way around - RedPRL rules into Z3 (SMT-LIB) assertions?
Or how do you see this integration.I've heard about Isabelle's Sledgehammer but never used it. :)

**Comment by favonia** [comment]
@gabriel-fallen To use the SMT solvers effectively, certainly we need to translate judgments in the context into SMT assertions. However, after that, we should then translate a proof generated by SMT solvers back into a combination of tactics and rules in RedPRL, so that we only have to trust the RedPRL core rules. Currently Z3 can output a proof, and I believe Isabelle is doing what I described here. Did I answer your question?

**Comment by jonsterling** [comment]
Alternatively, we could have a mode for running RedPRL where we just trust the solver by FIAT; this rule could target only those cases where we don't care about the witness (like membership and equality).

I think even that would be pretty cool! Obviously it would be extremely cool to render Z3 proofs into RedPRL scripts.

**Comment by favonia** [comment]
@jonsterling I thought maybe there are cases where the solver can give a witness but not a proof of correctness? I don't have a concrete example in my mind.

**Comment by jonsterling** [comment]
@favonia Ah, that's a great point that I didn't think of! Yeah, we could also give a rule for those cases too 😄

**Comment by gabriel-fallen** [comment]
@favonia yep, you totally answered the question, it's clear to me now.
Though, when you say "Z3 can output a proof" do you mean a model in SMT sense when all constraints are satisfiable?

**Comment by favonia** [comment]
@gabriel-fallen Probably---I have not really looked into SMT solvers in details. I am worried that the "model" defined in the SMT standard is not strong enough for RedPRL proof reconstruction.

**Comment by favonia** [comment]
I just learned from Natarajan Shankar (SRI) that CVC4 is another tool we can look into.

**Comment by gabriel-fallen** [comment]
Since Microsoft changed Z3 license to MIT there are almost no reasons left to prefer CVC4. 😆 
Frankly speaking I worked with Z3 a little but only looked at CVC4 documentation, so I'm biased. :)

**Comment by gabriel-fallen** [comment]
Regarding SMT model and proof reconstruction, that completely determined by RedPRL rules/tactics encoding being implemented. At the moment I can't imaging appropriate encoding (most likely because I haven't read RedPRL papers :)), but Sledgehammer somehow does it for Isabelle rules and tactics.

**Comment by gabriel-fallen** [comment]
Another nice feature of Isabelle/jEdit, when you write down a theorem and starting a proof, occasionally Isabelle tells you "I don't think you'll be able to prove this statement as I found a counterexample. Here it is." I bet it does this with an SMT solver too, and maybe this feature is easier to implement.

**Comment by favonia** [comment]
@gabriel-fallen Well, there are no significant reasons left to prefer Z3 either... And, yes, the counterexample mechanism could be integrated; one potential problem is that the context might have other things that are not handed to the SMT solver. Anyways, I even want to see whether it makes sense to add conflicts (from a conflict-based algorithm) as lemmas (an idea I learned from Shankar).

**Comment by favonia** [comment]
I then learned from @blanchette that veriT is yet another one we can look into.
