### ISSUE TITLE
Syntax for the function application?

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#278]
I suppose we can have `(lam [x] a)` and `($ a b)` just like `(abs {i} a)` and `(@ a i)`? (The current pretty printer does not generate valid code.)

PS: Other minor things that I will update after #262 is done:
- `S1_REC`
- `PATH_APP`
- `APP`
- `S_IF`, `IF`, etc

**Comment by favonia** [comment]
Maybe we (or I) can implement n-ary applications like `($ f a b c d)` and `(@ p i j k l)`.

**Comment by jonsterling** [comment]
@favonia Yes, that's a great idea. I think that this kind of n-ary notation belongs in the parser and the printer, like we did for function types, etc.
