### ISSUE TITLE
Make 'auto' have "deep" alternative search

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-redprl#288]
The title of this ticket is not so clear, but let me explain.

Currently, when checking equations like `hcom = m` there is a choice between using cap-equality and tube-equality. Right now, cap-equality is favored, but this is not always the correct choice: sometimes both are immediately possible, choosing cap equality will ultimately result in impossible goals.

One way to resolve this is to have `auto` generate a kind of search tree, so that in places where there are multiple possible choices, we should actually try all of them! Then, `auto` would terminate when *one* of its search branches succeeds.

To do this, we should expose a primitive `Auto` tactic from the refiner, instead of the current implementation which actually *reduces* the tactic `auto` to an LCF recursive tactic.

**Comment by jonsterling** [comment]
To be honest, what would be cooler is to adjust the tactic superstructure to support something like `t1 ANDELSE t2`, which has a different semantics from `t1 ORELSE t2`. In particular, `(t1 ANDELSE t2) THEN t3` is the same as `(t1 THEN t3) ANDELSE (t2 THEN t3)`.

But that would be a difficult and invasive change; I will think about it.

**Comment by favonia** [comment]
For the current theory (I believe) there is a very good ordering of rules to avoid backtracking, but of course complexity can grow over time.

**Comment by jonsterling** [comment]
I already have very basic examples where hcom checks fail because of the ordering.

**Comment by favonia** [comment]
@jonsterling Can you show it? I would like to know.

**Comment by jonsterling** [comment]
Yes, I'll share when I get home :)

**Comment by jonsterling** [comment]
@favonia Here's an example you can play with:

```

Thm NatSymm : [
  (->
   [m n : nat]
   (path {_} nat m n)
   (path {_} nat n m))
] by [
  lam a. lam b. lam pab.
  // I'm using the primitive interface rather than "<i> ..." to avoid 'auto' getting called;
  // this way, we can expose and understand the problem.
  fresh i:dim <- auto-step;
  // for our first subgoal, provide the hcom explicitly.
  [`(hcom{0 ~> 1} nat ,a 
     [i=0 {j} (@ ,pab j)]
     [i=1 {_} ,a])];
  [?oh-no, // this is true by the tube rule, but that won't get called (I think the cap rule is getting called instead)
   ?fine; auto // this subgoal is fine, I think the cap rule gets called
   ]
].
```

**Comment by jonsterling** [comment]
It may be a premature head expansion that is the problem rather than the cap rule; I'm not sure.

**Comment by jonsterling** [comment]
Also note that the version of this theorem where nat is just `#A` works fine (that's what leads me to think this may be an issue with head expansion, but you would know better than I).

**Comment by favonia** [comment]
It seems to be a bug in the machine, the `Computation` family of tactics or the way `auto` is using it. Both sides should reduce to `,a` immediately, and then the membership is obtained from the context. Something is wrong but I believe is not about the cap rule.

**Comment by jonsterling** [comment]
@favonia Thanks for your comment! I think you are right. I have tried explicitly running head expansion and I do indeed get an incorrect result, so this indicates a bug in the machine. (!)

**Comment by jonsterling** [comment]
@favonia Oh, actually, I misread what was going on. I don't think that the machine is the problem, and it's not the case that both sides should reduce to `a`. The goal is: `(hcom{0->1} nat a ...) = b in nat`; then, the left-hand side reduces to `a` correctly, making our goal `a = b in nat`.

**Comment by favonia** [comment]
@jonsterling Unfortunately I am (slowly) updating the rules and cannot easily experiment this without ugly git-switching. The `b` seems to be generated from `(@ ,p 1)` which seems to indicate some bugs in the composition kit. Maybe I should clarify that, maybe there is a bug in the cap rule, but I don't think the *order* of applying rules is the problem.

**Comment by jonsterling** [comment]
@favonia OK, thanks! We can hold off on fixing this until you are at a less inconvenient point.

You know best about the composition kit.

**Comment by jonsterling** [comment]
I looked a bit more into it, and I'm not even sure that the bug is in the composition kit, but it's hard to tell. The impossible subgoal actually comes from `Path.True`, where it is checking that the sides of the constructed path match the specified endpoints.

Here is my new annotation of the proof script, with my thoughts on what is going on:


```

Thm NatSymm : [
  (->
   [a b : nat]
   (path {_} nat a b)
   (path {_} nat b a))
] by [
  lam a. lam b. lam pab.
  // I'm using the primitive interface rather than "<i> ..." to avoid 'auto' getting called;
  // this way, we can expose and understand the problem.

  // Now our goal is (path {_} nat b a)
  fresh i:dim <- auto-step;
  // Path.True is called by auto-step above, leading to three subgoals.
  [ // the first subgoal is to construct a line of naturals, which we do with an explicit hcom.
    // Let's call this hcom, which varies in direction 'i', H{i}.
   `(hcom{0 ~> 1} nat ,a 
     [i=0 {j} (@ ,pab j)]
     [i=1 {_} ,a]),

   // the next subgoal is to show that H{0} = b in nat (i.e. the left endpoint is correct). H{0} computes to 'a'
   // by head expansion, leaving the goal as a = b in nat.
   // The original goal is actually true though: by the hcom-tube equality rule, H{0} = (@ pab 1), which is equal to 'b'.
   // How do we induce the refiner to derive this?
   ?oh-no,

   // the next subgoal is to show that H{1} = a in nat (i.e. the right endpoint is correct). H{1} computes to 'a'
   // by head expansion, so this goal is trivial.
   ?asdf; auto];
].
```

P.S. Don't let this distract you from what you're doing, since this issue can be resolved separately.

**Comment by favonia** [comment]
Ah, interesting. The goal is actually semantically okay but our proof theory is currently too weak. The so-called "reflection" holds for `nat`.

**Comment by jonsterling** [comment]
@favonia Yeah; looking at it again, the problem does appear to be what I said in the beginning, which is that our proof theory calls certain rules in an order which won't work for this proof. I think that the rules themselves are correct (but not sure).

In my PR #290, I have added the ability to call primitive rules by name, and used that to demonstrate a version of the proof that does go through using the hcom/tube equality rules rather than what is done by auto: https://github.com/RedPRL/sml-redprl/pull/290/files#diff-872fd3ad100570ce1886cd414ca70ca8R77

```
Thm NatSymm : [
  (->
   [a b : nat]
   (path {_} nat a b)
   (path {_} nat b a))
] by [
  lam a. lam b. lam pab.
  fresh i:dim <- refine path/intro;
  #0 {
    `(hcom{0 ~> 1} nat ,a 
     [i=0 {j} (@ ,pab j)]
     [i=1 {_} ,a])
  };

  refine hcom/eq/tube;
  auto
].
```

**Comment by jonsterling** [comment]
I did some more checking, and the problem is not the order of hcom rules that get called—in fact, reversing the order has no effect on the example. The problem seems to be that we get into an unrecoverable state by means of head expansion; so maybe the answer is that we need to be a little more cautious about where we apply head expansion.

Originally I had thought that "head expand whenever you can" was universally good, but this example suggests that it might be fatal to do so in some cases. Maybe we can figure out a reasonable strategy.

**Comment by favonia** [comment]
What's the current situation and future plan for this issue?

**Comment by jonsterling** [comment]
@favonia Let's close this issue, and replace it with more specific problems as we encounter them.

**Comment by favonia** [comment]
I discovered an inactive branch `issue-288`. Is it still useful?

**Comment by jonsterling** [comment]
@favonia I think there is nothing useful in there; we can delete it.
