### ISSUE TITLE
Wild idea: remove notion of symbols and parameters altogether?

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-redprl#301]
RedPRL's syntactic framework is two-level: there is a theory of parameters, and then second-order operator signatures are indexed over this theory. Then, the second-order theory is generated from such a signature.

This makes the most sense in the semantics (especially for languages like those defined in PFPL, where parameter binding is substructural), but in the implementation of RedPRL, it has admittedly led to a lot of difficulties and duplicated work without much in return. **Moreover, since RedPRL's dimension theory is cartesian, binding of dimensions and of object variables has exactly the same meaning.**

(Here it is important to avoid a misconception that was promulgated in the discussions of CHiTT, where we said that "at the syntactic level, dimensions are treated as nominal atoms"; this statement really meant to refer to the *operational level*, not the syntactic level. The precise way to say it is that the syntax is cartesian, but that the operational semantics as a transition system enjoys naturality only with respect to permutation maps.)

What we gain from the implemented style is that we can have operators which take a name as a parameter, and this name participates in the parameter-bindings. Currently the places where this matters in a crucial way have nothing at all to do with dimensions; it has only to do with hypotheses in the proof theory, where it is nice to have "elim" take an honest-to-god hypothesis name as a *parameter* rather than take an argument and force it to be a variable.

One other nice thing that we get is that the operational semantics is completely driven by the shape of the head-operator, and each step is "parametric" in the exact materials that lie in the subtree of an operator. **I felt that this was very important from the start, but I wonder if it really matters for implementation.**

But I think that the above is not enough to get in return for the amount of effort we have put in. I would like to consider regarding dimensions as terms of sort `DIM`. We would change the syntax for things like `hyp` and `elim` tactics to take a term argument rather than a "name".

+ *This would also allow us to get rid of the `,x` stuff in terms that you supply to the refiner, which has always felt like a hack.*
+ We can also get rid of the `PARAM_EXP sigma` sort
+ We can get rid of the `PARAM_SUBST` "judgment" and just use ordinary substitution and metavariables.

Since RedPRL is the only client of the ABT library, we could remove support for symbols from it as well. This is a bit of a retreat, since that stuff would be useful for implementing stuff from PFPL using Bob's Thought, but I think it is unrealistic to expect that to happen at this point.

**Comment by jonsterling** [comment]
This would also enable #300 to be accomplished more easily.

**Comment by favonia** [comment]
Another tricky spot is operators with varying arities like `hcom` and `com`, but I believe we can make them work by having families of operators.

**Comment by jonsterling** [comment]
@favonia Yes.

**Comment by favonia** [comment]
> One other nice thing that we get is that the operational semantics is completely driven by the shape of the head-operator, and each step is "parametric" in the exact materials that lie in the subtree of an operator. I felt that this was very important from the start, but I wonder if it really matters for implementation.

Again, I think `fcom` would the most annoying case if we turn `DIM` into an expression sort. We might have to inspect the subterms eagerly in a strange way, or when we encounter a variable of sort `DIM` it does not mean it is a neutral term, etc. These are still doable though, and I think `PARAM_EXP sigma` is too ugly which justifies any other ugliness.

**Comment by jonsterling** [comment]
@favonia Yeah, I think I agree with what you've said. Some things (like `fcom`) may be weird, but ultimately fewer things will be ugly. (I think).

**Comment by favonia** [comment]
Another issue: ideally the numeral `1` can be a dimension expression, an integer and a universe level. When should we disambiguate them? A tricky case for the parser is `customOpParams` because the sorts are not structurally determined. Or, should we give up the overloading by having `{level 0}` or `{dim 0}`? I bring this issue up here because turning `DIM` (or may `LVL` as well) into an expression sort will make the numeral overloading worse.

**Comment by jonsterling** [comment]
This is a bit tricky isn't it... Some thoughts:

1. No matter what, `0,1` should be dimensions.
2. We can have a parser for universe expressions, there is no need for overloading here. But there is the question of how to write a level on its own (as opposed to as part of a universe expression), and for that it might be just fine to write `{level 0}`, or whatever.

**Comment by jonsterling** [comment]
> We can have a parser for universe expressions, there is no need for overloading here

(What I meant by this is that we could parse `(U 0 kan)` or whatever without ambiguity)

**Comment by favonia** [comment]
We could parse `{loop 1}` or `{univ kan 1}` while in general have `{dim 1}` and `{level 1}`. I guess you meant we should have `{int 1}` for integers and `1` for dimensions, right?

**Comment by favonia** [comment]
I personally feel I need to write `{int 1}` more than `{dim 1}` so I prefer `1` to be `{int 1}` (`{dim 1}` is used a lot but mostly in the positions where sorts can be determined easily). I am worried about the typed parameter stuff since I did not write the code of it.

**Comment by jonsterling** [comment]
@favonia I don't know... Honestly are we really going to be doing a lot of numerical proofs in RedPRL that involve writing specific numerals? it seems pretty rare in practice, even if a lot of examples involve it right now. But maybe I am mistaken...

**Comment by jonsterling** [comment]
I would prefer not to burn time bikeshedding about notation/minutia, so feel free to use whatever notation you want, and we can always improve it in the future.  😄

**Comment by favonia** [comment]
Alright, I will disable overloading except for "obvious places" for now.

**Comment by favonia** [comment]
How exactly do you want to get rid of `HYP_REF`, if you want to? Do they become regular expression variables?

**Comment by jonsterling** [comment]
I am not yet sure how to deal with hyps; if we undertake this, that will be the last stage I think.

**Comment by favonia** [comment]
Another question: if we migrate universe levels to expressions, what should be a level variable binder?

**Comment by jonsterling** [comment]
@favonia I don't yet understand your question about level expression binders; can you elaborate or give an example of what you mean?

**Comment by favonia** [comment]
Eventually we can say something like this:
```
Thm Univ0{i:lvl} : [
  (univ i cubical) type
] by [
  auto
].
```
where `i` bound. I wonder what should be the binder if levels become expressions.

**Comment by jonsterling** [comment]
Ah, I see! Then it would be an argument, specified like Thm Univ0(#i:lvl) : [(univ #i cubical) type]...

**Comment by favonia** [comment]
If so, I am worried that we have to handle
```
Thm Univ(#x : dim, #i : exp -> lvl) : [
  (univ (#i base) cubical) type at (#i (loop #x))
] by [
  auto
].
```
or something weird like that.

**Comment by favonia** [comment]
It is kind of weird for the level module to allow arbitrary subterms in the levels. I would like to reject even the following example if the mix of `lvl` and `exp` is unavoidable.
```
Thm Univ(#i : [exp].lvl) : [
  (univ (#i base) cubical) type at (#i base)
] by [
  auto
].
```

**Comment by favonia** [comment]
@jonsterling, @RobertHarper mentioned the `world` constraints in twelf which I think are relevant. Have you thought about including this feature in the abt library? Basically we (or at least I) want to express the constraint that nothing of sort `exp` can appear in something of sort `lvl`, etc.

**Comment by jonsterling** [comment]
@favonia That's a very cool feature, but I don't think it is necessary here (though I could be wrong).

In particular, I think there is nothing wrong at all with having a level expression which mentions an expression variable—by the way, regardless of what you do here, this state of affairs will absolutely be induced by dependent refinement, since we will end up having metas ranging over levels! And that's perfectly fine, there is no problem with it.

Your example (with `(#i base)`) is semantically perfectly sensible, by the way, there is no need to rule it out (even if it seems 'weird').

**Comment by RobertHarper** [comment]
Hmm, I need to understand this, because to me parameters such as universe levels are "prior" and independent of ordinary expressions.  Eg, I doubt there is a function from nat to types that yields Ui given i .

Bob

(c) Robert Harper. All rights reserved.

**Comment by favonia** [comment]
@jonsterling To clarify, I am fine with the sort `[lvl].exp` but find the sort `[exp].lvl` suspicious. The meta variables ranging over levels sound like `[lvl].exp` to me. Semantically with these constraints I think it is easier to prove adequacy (if we care). Otherwise, yes, it's probably okay because we can probably show it must be a constant function or something, but I doubt if there is a good use of `[exp].lvl`...

**Comment by jonsterling** [comment]
@RobertHarper 

> Hmm, I need to understand this, because to me parameters such as universe levels are "prior" and independent of ordinary expressions.  Eg, I doubt there is a function from nat to types that yields Ui given i .

So, the reason there is no such function is not a syntactic constraint (though there is not currently a way to write this code, there is nothing stopping us from adding that), but that there is no universe big enough to contain the type of such a function.  So, you could (potentially, with some changes) write that code, but you shouldn't be able to show that it inhabits a function type.


@favonia Yes, I mean that there is nothing wrong with a binder `[exp].lvl`. These could come up during proof refinement; in fact, they *will* come up if there is any judgment whose extract is of sort `lvl`. Again, semantically I think there is no problem with this (but I'm very open to hearing your ideas about what might go wrong or be suspicious about it).


Ultimately, I think all this comes back to the Nuprl/CTT methodology which is that you can write all sorts of syntax, and all sorts of 'programs' which seem weird, but ultimately you have to bring the goods: the goods, in this case, being a mathematical argument that some program inhabits a certain type.

**Comment by favonia** [comment]
Alright, but for the proof theory, can we ignore those potentially higher-order stuff? Solving inequalities involving functions (and maybe higher-order functions) seems extremely difficult.

**Comment by jonsterling** [comment]
@favonia Yes, I think that's the right way to think about it. We shouldn't try to solve those things, or really do anything overly sophisticated here; it's fine if the proof theory isn't "complete" (it will never be), so we can never go wrong by being too conservative.

**Comment by jonsterling** [comment]
This has now been done for universe levels; the hardest one to do is dimensions, because it entails changing the syntax of compositions quite a bit.

**Comment by RobertHarper** [comment]
yeah, in the computational setting it may not make as much sense as it did in the formalisms of my book.  i even found it hard, at first, to see this, but it may be so.

otoh, karl and i are extending lf with parameters and symbols, just to have a framework that can cover everything in my book!

bob

(c) Robert Harper  All Rights Reserved.

**Comment by jonsterling** [comment]
@RobertHarper Yeah... I also think that for things like giving a mathematical description of the language, the symbol & parameters stuff from your book makes a ton of sense and is pretty important; but I'm finding that there is a mismatch at the level of implementation. It's likely that it's still possible to come up with an implementable version of all this stuff that is way better; I think that right now, one of the main reasons it makes sense to change it is not that the idea from PFPL is not applicable, but because my implementation is unwieldy.

I'm looking forward to seeing a version of LF with all this stuff :)
