### ISSUE TITLE
Correctness of Hyps.Delete

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#310]
Did we prove strengthening somewhere? I actually thought it is false. @cangiuli

**Comment by jonsterling** [comment]
If strengthening were false, that would be very surprising & confusing... At least as far as the proof theory is concerned, it seems unlikely that there is any proof which can be done "without using" a hypothesis, but which cannot be done "without" that hypothesis being "existing".

**Comment by favonia** [comment]
I think we can prove `a:Void >> whatever` without mentioning `a` in the current implementation. Maybe it's time to rethink about `Void-elim(a)`?

**Comment by favonia** [comment]
Actually, I feel one can still work around it even with `Void-elim`....

**Comment by jonsterling** [comment]
Hmmmm, maybe so... Let me think about it a bit.

**Comment by jonsterling** [comment]
@favonia I got confused; `Hyps.Delete` is not strengthening, but actually weakening! (The nature of backward inference gets my mind reversed sometimes.)

All that `Hyps.Delete` says is, "To show `J` assuming `x:A`, it suffices to show `J` without assuming `x:A`."

**Comment by favonia** [comment]
@jonsterling Oh, I see.
