### ISSUE TITLE
Correct Nat.Elim without higher-order LF

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#311]
@cangiuli @jonsterling We should try to figure out the correct version of `Nat.Elim` without higher-order LF. The task is to eliminate `x:nat` from
```
Gamma0, x:nat, Gamma1 >> c true.
```
When `Gamma1` is empty, I believe it's safe to refine this into two subgoals:
```
Gamma0 >> c[0/x] true.
Gamma0, y:nat, z:c[y/x] true >> c[succ y/x] true.
```
However, I am not sure what to do with non-empty `Gamma1`.

**Comment by jonsterling** [comment]
Why does it matter whether `Gamma1` is empty? Also, why not just follow the rules given in Nuprl which do not require any higher order framework? See the integer elimination rule from Nuprl:

![screen shot 2017-08-07 at 8 26 36 pm](https://user-images.githubusercontent.com/55057/29051195-d52ad6e8-7bae-11e7-96fb-eeec9e9dba55.png)

**Comment by jonsterling** [comment]
Now I can't remember why I thought the left rule required a higher-order LF—Bob convinced me at one point, but I can't remember why. @cangiuli do you remember?

**Comment by favonia** [comment]
@jonsterling I think this is maybe the "weaker" form because it is not doing induction on the entire sequent, and maybe this is what we can achieve at best. This also connects to my previous question whether we want to link `z` and `x`. In the above rule, the answer is no.

**Comment by jonsterling** [comment]
@favonia That's a good point (re: it not doing induction on the full sequent); I think we should start with this rule, and then we can discover whether we actually need more than this. I have a feeling that the stronger cases could be encoded in some cases using function types, especially once we have more of your stuff in place. It's telling that Nuprl doesn't need anything more than this, and they have done a lot of gnarly stuff with integers and nats...

Re: whether `z` and `x` are related, that's another good observation, thanks for pointing it out; I think that we ultimately need them to be related for things like function types, but for this we should leave them not equated.
