### ISSUE TITLE
Consider requiring hypotheses to be `A true`

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-redprl#319]
Now that @favonia has implemented this cool kind lattice thing, it is possible for us to begin revisiting the design of RedPRL's proof theory with an aim toward simplification. 

One thing that might make sense in the near term is to require the hypotheses in a sequent to all be of the form `A true with k`; to be precise, each hypothesis would just be a pair of a type and a kind. This would simplify and clarify the meaning of RedPRL sequents, especially as far as functionality is concerned.

We would still want the conclusion to be an arbitrary categorical judgment.

In order for this to work, we need:

- [x] Equality types
- [x] Universes

There's also some dark bits of RedPRL that I (JS) would have to change, but that I could certainly do that if we felt it was a good idea.

**Comment by favonia** [comment]
With equality types, can we ban equality judgment now? To be more precise, only `true` and `eqtype` will be allowed in the context. After we have the universe the `eqtype` can be banned as well.

**Comment by jonsterling** [comment]
@favonia It would be weird to prevent only some non-`true` judgments from appearing in the context. We should wait until we can do this systematically.

**Comment by favonia** [comment]
@jonsterling Hmm... we can also try to work out a cubical universe first, but I already have some ugly proof involving equality now.

**Comment by favonia** [comment]
Could we make it `A true with k at i`? A complete description of a universe involves (1) the kind and (2) the level (the size), so we can demand that everything in the context must be a triple `(type, kind, level)`.

**Comment by jonsterling** [comment]
@favonia Yeah, I was thinking we might want something like that... I think the only difficult thing is that since RedPRL's refinement stuff doesn't support "multiple outputs" primitively, I guess we would need to have a sort for these triples and then need to actually have some judgments for projecting things out of it. All this can be papered over using helper functions, though.

**Comment by favonia** [comment]
> actually have some judgments for projecting things out of it

Are you suggesting three new categorical judgments `PROJ_EXP` `PROJ_KIND` and `PROJ_LEVEL` which somehow gets these from something of sort `STRATIFIED BLAH`? Actually, due to these complexities I am giving up the idea of returning the strongest kind.

**Comment by favonia** [comment]
Actually, now I feel turning every `EQ`/`EQ_TYPE`/`TRUE`/`SYNTH` goal into three goals is still too much. How much work do we need if we are determined to support multiple outputs denoted by `sort list`? In my imagination, `hyp a` would additionally take an index, denoting the index of the output we want. We can then remove the `TRIV` sort and `TV`. We can probably simplify some use of `MATCH` in `refiner_types` as well.

**Comment by jonsterling** [comment]
> Actually, now I feel turning every EQ/EQ_TYPE/TRUE/SYNTH goal into three goals is still too much

Yeah, I was wondering whether that would be too horrible to do... I think you're right. I'm not yet exactly sure how to support multiple subgoals in the implementation, but if it is a priority, I can begin to think about it again...

**Comment by jonsterling** [comment]
> In my imagination, hyp a would additionally take an index, denoting the index of the output we want. 

Hmm, interesting... I think that the issue is we really need to support multiple outputs at the level of the framework, unless you can think of a way around this. That means that the general form of a telescope would be like `[x,...] : J, ...` and a validation would actually be a list of validations.

**Comment by jonsterling** [comment]
I think there may be a way to support this that is not *too* disruptive, but I have to think about it a bit. I'm busy feeding the poor today, but I will resume thinking about it this week.

**Comment by favonia** [comment]
> a validation would actually be a list of validations.

That is probably doable, but the telescope library will be challenging to implement correctly. For example, how should splice work if it only replaces one of the output? I then gave up this idea and proposed
```
x : J >> ... hyp x 0 ...
```
where `hyp x 0` refers to the first output of `J`. Every output is then inherently a list, and you have to specify the index in later hypotheses or the conclusion.

**Comment by jonsterling** [comment]
> That is probably doable, but the telescope library will be challenging to implement correctly

I think we can "simulate" this without changing the telescope library; but I'm not certain yet.

Your idea about `hyp x 0` sounds very interesting, but I don't understand how it actually addresses what needs to be done to support multiple outputs (or at least, resolve this particular issue that we are talking about). Could you go into a bit more detail?

**Comment by favonia** [comment]
Let's suppose `SYNTH (zero, k)` now synthesize `LIST [EXP, EXP]` where the first one is the type and the second is the dimension. Eventually this should be provable:

``x : SYNTH (zero, k) >> (hyp x 0) in (univ k (hyp x 1))``

The sort checking recognizes that if `x` is of sort `LIST l`, then `hyp x n` is of sort `l !! n`.

**Comment by jonsterling** [comment]
I don't understand your example—why would `SYNTH` produce a dimension?

More generally, I am not crazy about this idea because it seems to mean that *programs* themselves would have these projections rather than ordinary variables *in their syntax*.

**Comment by favonia** [comment]
Sorry it is not producing a dimension but a _universe level_.

As I said, you could name each projection, but then I believe you would have to either (1) somehow name the collection of projections from the same hypothesis or (2) having separate categorical judgments or adding indexes in the type of hypotheses for different outputs, like `(SYNTH ..., 0)` which generates the first output and `(SYNTH ..., 1)` which generates the second one.

**Comment by favonia** [comment]
In the first approach, the following is provable

```
xy as [x, y] : SYNTH (zero, k)
--------------------------------------
 (hyp x) in (univ k (hyp y))
```

but `splice` and `interpose` can only take `xy` as the argument. In one possible implementation of the second approach, the following is provable:

```
x : (SYNTH (zero, k), 0)
y : (SYNTH (zero, k), 1)
--------------------------------
(hyp x) in (univ k (hyp y))
```

and the telescope is essentially the same. In another implementation, this could be

```
x : SYNTH0 (zero, k)
y : SYNTH1 (zero, k)
--------------------------------
(hyp x) in (univ k (hyp y))
```

**Comment by favonia** [comment]
Everything can be internalized directly except the cases where we want to prove two types are equal but we don't care the level they're at. Nuprl demands the user or its synthesizer to figure out the level.

**Comment by favonia** [comment]
@jonsterling I feel we are ready to tackle this issue...? I kind of want to wait for this issue before looking at #322 and others. To be clear, everything in the context will have the form

x : A with k at l

as the current `TRUE` judgments. That is, `abt * kind * level option`.

**Comment by jonsterling** [comment]
It does seem like we are ready!

**Comment by jonsterling** [comment]
@favonia I talked with Evan and now I think we may not want to do this just yet. We will still need separate forms of judgment to talk about things that we can't internalize, such as computational equivalence (whatever that ends up meaning, it will most likely not be internalizeable).

I'm going to hold off, but at the same time, I will see if I can make those "dark areas" less dark.

**Comment by favonia** [comment]
Ah, I forgot we want to hold off. Reverting the changes in my local copy...
