### ISSUE TITLE
Error messages and exceptions

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#324]
Should we define different kinds of exceptions, throw them instead of formatted error messages, and only turn them into messages much later?

**Comment by jonsterling** [comment]
@favonia I think that's a very good idea! We can put these in the `RedPrlError` module... I think we can make this change incrementally rather than all at once, and it will increase the clarity and modularity of RedPRL.

**Comment by favonia** [comment]
How should I do this? Just declare new exceptions in RedPrlError as I like it?

**Comment by jonsterling** [comment]
@favonia Go for it as you like!

**Comment by favonia** [comment]
@jonsterling Is there some good documentation on `Fpp.align` and `Fpp.nest`? I do not feel I understand them well.

**Comment by jonsterling** [comment]
@favonia Check out http://davidchristiansen.dk/drafts/final-pretty-printer-draft.pdf for a description of the library.

**Comment by favonia** [comment]
This is actually done.
