### ISSUE TITLE
Kan operations of composition and V types

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#330]
0. ~Fix various stuff to make universes really work (except their Kan operations).~
1. ~`MEET_WITH_COMPLEMENT` and unify kinds and levels more.~
2. `fcom`
    a. ~hcom for universes.~
    b. ~`Restriction` combined with `makeEq`, and conditional goal making in cap/tube coherence subgoals.~
    c. ~Heterogeneous formal composition delegate.~
    d. hcom and coe operators for `fcom`.
3. ~Only true judgments can be hypotheses. #319~

**Comment by jonsterling** [comment]
This all sounds fairly reasonable, but why are the following part of the tasks for building universes?

> Turning kinds, levels and dimensions...

> Only true judgments can be hypotheses...

Aren't these orthogonal?

**Comment by favonia** [comment]
I guess I don't want to implement Universe.Eliminate and then remove it. The expression stuff is again to avoid working hard with param_exp and then dropping it. Let me change the first item to "wait" though.

**Comment by jonsterling** [comment]
@favonia OK! By the way, feel free to do things in whatever order you feel is best, and if you feel it will be better to make all those changes in this order, then please do so. I trust your judgment.

**Comment by favonia** [comment]
@jonsterling Actually, you were right. I should not wait for #301 as there are still some design issues left.

**Comment by jonsterling** [comment]
Are the operational semantics for `hcom` and `coe` on `V` types written down in a note somewhere?

I was going to try out an example like:

```

Thm NotV/test2 : [
  (= bool (coe 0~>1 [i] (NotV i) tt) ff)
] by [
  ?
].
```

**Comment by favonia** [comment]
@jonsterling You should ask @cangiuli about the latest paper version. I did not implement them because we sort of agreed to finish other parts first, and that "other parts" in my opinion are not done yet. Otherwise I can finish the implementation in no time.

**Comment by jonsterling** [comment]
@favonia OK! There's no need to rush, I was just curious.

**Comment by cangiuli** [comment]
Feel free to implement them. I think all of us (and also Anders!) would like to see them in action.
