### ISSUE TITLE
Generalize `HCom.Cap`, `HCom.Tube`, `Coe.Cap` and `Path.AppConst` to handle types.

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#336]
With the universes, everything is possible. See the discussion in #335.

**Comment by jonsterling** [comment]
@favonia Is this still necessary now that we have universes? Just curious.

**Comment by favonia** [comment]
This was not solved by the introduction of the universes; rather, it was raised by the introduction. However, this is closed by #502.
