### ISSUE TITLE
Defining categories?

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-redprl#347]
Here's an example of something I'd like to be able to write:

```
Thm Category{i:lvl} : [ (univ {lsucc i}) ] by [
  exact
   (record
    [ob : (univ i)]
    [hom : (-> ob ob (univ i))]
    [idn : (-> [a : ob] ($ hom a a))]); // fill in the rest, but this suffices as an example
  ?
].
```

But I can't seem to prove the wellformedness lemma. It would be nice if it were done automatically, but I'm not sure if it is even provable manually. Any thoughts?

**Comment by favonia** [comment]
First of all we probably need #322. You can see what's going on by
```
Thm Category{i:lvl} : [ (univ {lsucc i}) ] by [
  exact
   (record
    [ob : (univ i)]
    [hom : (-> ob ob (univ i))]
    [idn : (-> [a : ob] ($ hom a a))]); // fill in the rest, but this suffices as an example
  refine univ/eq;
  fresh ob, hom, idn -> refine record/eqtype;
  [ auto
  , auto; fresh ob' -> elim ob; ?hole1
  , auto; fresh ob' -> elim ob; ?hole2
  ]
].
```
The first hole should be solvable by `use ob'` once #322 is done. The extra elim will have to go away when #319 is done or when someone (you or me) feel too frustrated. After these two I suppose the second hole would be easier...

**Comment by favonia** [comment]
I then guess you also want `refine univ/eq` to be part of `auto`. I have not done that yet, and I could try that if you have not done it when I come back from #338.

**Comment by jonsterling** [comment]
@favonia Well, for now I'd be happy if I knew how to prove this manually 😆

**Comment by jonsterling** [comment]
Oh, I didn't see your first comment!

**Comment by favonia** [comment]
Maybe before #322 we can also enhance one of the `XFromY` to take level inequalities into consideration. Basically everything that handles subkind relations should handle level inequalities as well.

**Comment by jonsterling** [comment]
That'd be sweet!

**Comment by favonia** [comment]
The funny thing is that the first hole can be filled directly by `auto`... I guess I made `auto` too powerful without increasing the manual weapons (`use`) proportionally.
