### ISSUE TITLE
Consider completely removing type equality/typehood judgments

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-redprl#351]
And replacing them with member equality judgments, using the universe.

This would simplify automation quite a bit, I think. What do you think @favonia? Do we lose anything if we do this?

**Comment by favonia** [comment]
I thought you want level synthesis? Without it, I believe the only thing we cannot internalize is the following judgment:

A and B are equal types at some *unknown, finite* level.

The Nuprl would ask for or infer the level as an input to the tactic/rule. One example is `dfun/eq/lam` (`DFun.Eq`) where we have to make sure the domain is a type.

**Comment by jonsterling** [comment]
@favonia 

1. I'm OK with not having level synthesis generally; it's a cool thing, but I don't think it's as important as it sounds.

2. Ahh, you're right about `A = B type` with an unknown/unrestricted level! That may be the sticking point that requires us to keep this form of judgment. It was always annoying in Nuprl and JonPRL to have to put in a level by hand there.

**Comment by favonia** [comment]
And this will be possible again after implementing the plan in #407.

**Comment by favonia** [comment]
@jonsterling Actually, it seems the equality judgments can already be removed. Would you mind changing the title?

**Comment by jonsterling** [comment]
@favonia Which equality judgments? the type equality ones or the member equality ones? (I assume the latter)

**Comment by favonia** [comment]
Yes, member equality ones.

**Comment by jonsterling** [comment]
@favonia I've opened a new ticket for that, and we can leave this ticket open for tracking the question of *type* equality judgments.

**Comment by favonia** [comment]
@jonsterling Well, there is already #407 for type equality judgments, right?

**Comment by favonia** [comment]
Closed as this was split into #407 and #457.
