### ISSUE TITLE
grammar of typehood judgments is confusing

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-redprl#352]
It looks like we have `A type at k` and `A = B at k type`; it might be clearer to have `A = B type at k`. Unless I misunderstood the grammar.

**Comment by favonia** [comment]
There are levels and kinds. The current full grammar is
```
A = B k type at l
M = N in A type at l with k
```
and various components will be hidden under various conditions.

**Comment by favonia** [comment]
I am all ears for grammar suggestions because my English is terrible.

**Comment by jonsterling** [comment]
> I am all ears for grammar suggestions because my English is terrible.

It's continued to improve and it's already pretty good! 😄 

I'll circle back to this issue soon, I need to stop procrastinating on my TA duties.

**Comment by favonia** [comment]
Any suggestion for the new grammar? I am tweaking the parser now.

**Comment by favonia** [comment]
Turns out `A = B at k` is due to a bug. `term EQUALS term atLevel kindedType` should have been `term EQUALS term kindedType atLevel`.
