### ISSUE TITLE
Support underscores in patterns

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#356]

**Comment by jonsterling** [comment]
Like in the `match` thing? I think that'd be doable...

**Comment by favonia** [comment]
I haven't tried underscores in `match`. I meant something like `lam _. blah`.

**Comment by jonsterling** [comment]
@favonia Ah! yes.

**Comment by jonsterling** [comment]
I just checked and this works now, I must have fixed it at some point.
