### ISSUE TITLE
unfold/reduce only the goal or some hypotheses

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#359]
Possibly four tactics in total? Also maybe some auto-unfolding/head-expanding before `AutoElim`.

**Comment by jonsterling** [comment]
What would be nice is to have this handled in one tactic with an argument, like:

```
  unfold op in target, ...
```

where 

```
target ::= x | concl
```

**Comment by favonia** [comment]
Hmm is there a way to avoid adding another keyword `concl`?

**Comment by jonsterling** [comment]
@favonia I'm not sure... Probably you'd need to add a keyword. We have too many keywords in RedPRL already, but I'm not sure of a way around it.

In the new order (i.e. the new metalanguage) we'll have far fewer keywords, fwiw.

**Comment by favonia** [comment]
I think I am happier with
```
target ::= x | goal
```
because `goal` is already a keyword. Also would you mind renaming `head-expand` to `reduce` or `eval`?

**Comment by jonsterling** [comment]
1. `goal` is fine 😄 
2. feel free to rename as you please

**Comment by jonsterling** [comment]
I prefer `reduce` for the latter

**Comment by favonia** [comment]
So...
- `unfold X`: unfold X everywhere.
- `unford X in a, b, c, ...` and `a := x | goal` unfold `X` in those places.
- `reduce`: reduce everywhere
- `reduce at a, b, c ...` and `a := x | goal` reduce at those places.

All the above tactics only work on the sequents `>>`.

**Comment by jonsterling** [comment]
This sounds perfect!

**Comment by favonia** [comment]
@jonsterling Turns out the grammar is faulty... Could you remind me again the reason you added commas between the bound variables in `lam a, b, c.`? -Favonia

**Comment by jonsterling** [comment]
@favonia I think the reason was just that it felt more consistent for the notation of the tactic language. But I don't care, please feel free to change the grammar in *any* way you like.

**Comment by favonia** [comment]
The annoying thing right now is that the commas are also used in `[tactic1, tactic2, tactic3]`. Without an ending symbol, `[unfold Blah in x, goal, y]` could be problematic.

**Comment by jonsterling** [comment]
Right; one way to get around the issue is to have require a delimiter in `unfold Blah in [x, y, ...]`. Another way would be to remove the commas perhaps. I don't have any preference though, so you can feel free to pick what looks best to you.

**Comment by favonia** [comment]
Hmm the current implementation is not good enough. The order of those `opids` should not matter.

**Comment by jonsterling** [comment]
@favonia Are you proposing to repeatedly unfold until quiescence? or something else?

**Comment by jonsterling** [comment]
I wonder what the behavior is in Coq.

**Comment by favonia** [comment]
@jonsterling I meant currently `unfold [opid0, opid1]` and `unfold [opid1, opid0]` are different, but they should be the same.
