### ISSUE TITLE
New atomic judgments---SUBTYPE?

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#364]
@jonsterling @cangiuli It seems difficult to support subtyping without a new judgment form. The tricky case is
```
a : A, f : (-> A B) >> ($ f a) in B'
```
where `B` is a subtype of `B'`. The current rule will infer that a type of `f` is `(-> A B)`, and then insist on the equality between `B` and `B'`. Even worse, when this goal is generated, the "`B`" is just a meta-variable in that goal. It seems there is no easy way to support subtyping without a dedicated judgment holding the unresolved subtyping relation.

**Comment by jonsterling** [comment]
I think it's a reasonable idea... I wonder if we can somehow generate the equality and subtyping goals from a single spec (not necessary but maybe interesting).

**Comment by favonia** [comment]
By the way, we could _define_ `SUBTYPE (ty0, ty1)` as `TRUE (-> [x : Ty0] (= Ty1 x x))`.

**Comment by jonsterling** [comment]
@favonia indeed; another way to define the subtype relation (which they use in Nuprl) is `MEMBER (lam [x] x) (-> ty0 ty1)`.

**Comment by favonia** [comment]
@jonsterling Hmm... any reason to use a longer definition?

**Comment by jonsterling** [comment]
@favonia I'm not sure; I have a feeling that these are basically equivalent.

**Comment by favonia** [comment]
This was added as an atomic judgment now.
