### ISSUE TITLE
Tactics to synthesize the motive of `(nat-rec x ...)` automatically.

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#371]

**Comment by jonsterling** [comment]
That'd be sweet; do you think it is possible to synthesize it in general?

1. If we can do it in the general case, then that should be built into the proof theory / rules.
2. If we can only synthesize it in some cases, we should probably implement that behavior in a builtin tactic.

What do you think?

**Comment by favonia** [comment]
The same idea applies to `(if x ...)` and `(int-rec x ...)`. However, even if the motive can be synthesized, this is not always the correct choice. The only case that can definitely be automatized is
```
(nat-rec x ...) in C
``` 
where `x` does not appear in `C`.

**Comment by jonsterling** [comment]
Since we can't synthesize this automatically in a way that is generally correct, I'm not really sure what to say about this ticket...

**Comment by favonia** [comment]
Maybe what I was asking for is some pattern matching with variables or something like that. Is it possible to write a user-land tactic which extracts the motive, assuming every occurrence of `x` in `C` is used?

**Comment by jonsterling** [comment]
@favonia I'm not sure if it is yet possible to write this in userland, but hopefully it will eventually be possible.
