### ISSUE TITLE
Terminology clean-up: goal, sequent and conclusion

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#374]
This is related to #359. A "goal" should always mean an open end during refinement, not the conclusion in a sequent goal. Proposed changes:

0. Keyword `goal` to `concl`.
1. Constructor `IN_GOAL` to `IN_CONCL`.
2. Function `matchSeq` to `matchGoal` (this was the original name).

Any objection?

**Comment by jonsterling** [comment]
@favonia I'm happy with it!

**Comment by jonsterling** [comment]
(I mean, I like your proposal)
