### ISSUE TITLE
Allow `fresh` without a follow-up tactic?

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#376]
Currently, the grammar of `fresh` is `fresh blah -> foo; bar`. I feel we should also allow just `fresh blah -> foo`.

**Comment by jonsterling** [comment]
@favonia If we add this, it should be expanded during parsing to `fresh blah -> foo; id`, I guess.

**Comment by favonia** [comment]
That is certainly doable. In the beginning I thought we should ban this syntax, but then I realized the names  are probably visible in the `foo` tactic, and so they could be useful. Is my reasoning correct?

**Comment by jonsterling** [comment]
@favonia Yes, I think so. The semantics of tactic sequencing in RedPRL is that you are pushing names onto the stack for use (only) in `foo`.

Later, btw, I have plans to actually change the semantics of this name stack in a much more sensible way, but I'll wait to discuss that when I have a bit more bandwidth.
