### ISSUE TITLE
Reduce arguments of equal types.

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#382]
How about reducing the TRUE judgments of `(= ty m n) true` into `(= ty' m' n') true`? This is to bridge the gap between an `EQ` judgment and an internalized equality.

**Comment by jonsterling** [comment]
@favonia Such a rule seems semantically fine, but why not factor it through a roundtrip between the equality judgment and the internalized equality? that way we might not have to duplicate rules...

**Comment by favonia** [comment]
Hmm I meant changing the current behavior.

**Comment by favonia** [comment]
This will eventually be consumed by #393.

**Comment by favonia** [comment]
Needs to be done to make #457 practical.

**Comment by jonsterling** [comment]
👍
