### ISSUE TITLE
Example: Omega1(S1) = Z

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-redprl#383]
I think that we now have enough stuff implemented to prove that the loop space of the circle is the integers. This would be a great example to try, and would provide a point of comparison with the Swedish implementation (https://github.com/mortberg/cubicaltt/blob/master/examples/helix.ctt).

**Comment by jonsterling** [comment]
As a start, we can start proving some basic results about equivalences, such as "adjointification" (which takes an isomorphism to an VV-style equivalence): https://github.com/RedPRL/sml-redprl/commit/fe9ababa096e054df778b9ed0cf6bc135eebf524

I still need to fill in the hard part of this theorem, which looks like it will be a very gnarly nested composition (at least, if the Swedish version is any indication: https://github.com/mortberg/cubicaltt/blob/a331f1d355c5d2fc608a59c1cbbf016ea09d6deb/examples/equiv.ctt)

**Comment by favonia** [comment]
We need #330 to reduce `($ f loop^2)` to `2` by pure magic.

**Comment by favonia** [comment]
This was partially addressed by #420 and we need some machinery to proceed further.

**Comment by mortberg** [comment]
When you have done this please let me know so that I can compare with what I have in cubicaltt. 

A nice corollary that you could do once you have this is that the loop space of S^1 is a set. To prove this just transport the proof that Z is a set along the pi1(S^1) = Z equality. How complicated is the obtained term?

**Comment by favonia** [comment]
It would be great if we do not have to manually prove that
```
(S1-rec [_] (U 0 kan) (@ p 1) int [x] (@ IntSuccPath x))
```
is just
```
int
```

**Comment by jonsterling** [comment]
@favonia I was looking again at the "theorem" you sent me the other day which was currently hard to prove, and I realized that it's not well-typed:

```
Thm IntToS1LoopToInt/succ : [
  (-> [n : nat]
   (= int
    ($ S1LoopToInt ($ IntToS1Loop (succ n)))
    (succ ($ S1LoopToInt ($ IntToS1Loop n)))))
]
```

It's not well-typed, because `nat` is no longer a subtype of `int`, and also `succ` doesn't apply to integers.

Now, I did try replacing with `int` and `IntSucc`, but I didn't make much progress.
