### ISSUE TITLE
Add "top" level as a 'façon de parler'

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-redprl#390]
This would simplify the syntax quite a bit; judgments would be allowed to mention the 'top' level, but `U ltop` would not be a type. This would replace the optional-ness of level annotations in some judgments.

**Comment by favonia** [comment]
Yes we can do this. I did not do this purely because of trying to be excessively pedantic for the first experiment. One difficulty of super-clean-API is that the pretty printer needs to know whether it's omega or not. Or, we can just print "at omega" whenever the level is actually lacking.

**Comment by favonia** [comment]
Should we forbid `(lmax lomega lomega)`?

**Comment by favonia** [comment]
Same question for `(+ lomega 0)` and whether an exception should be thrown for `(++ lomega)`.

**Comment by jonsterling** [comment]
@favonia Would it be weird to have `(lmax lomega lomega) = lomega` and `(++ lomega) = lomega`?

**Comment by cangiuli** [comment]
> `(lmax lomega lomega) = lomega` and `(++ lomega) = lomega`

This is known as a 'parler trick'.

**Comment by favonia** [comment]
@jonsterling I am fine with `(lmax lomega lomega) = lomega` but not the other, because I wish `(U l)` is always a member of `(U (++ l))`.

**Comment by jonsterling** [comment]
@favonia Aha, I see! I think that is fair
