### ISSUE TITLE
MLton compiletimes have increased 10x

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-redprl#394]
It used to take only about a minute or two to compile with MLton, but now it takes more than 10 minutes. I wonder what happened!

I tried consolidating dependencies to avoid duplicating builds of (e.g.) CMLib, but this didn't seem to help at all.

**Comment by MatthewFluet** [comment]
Looks like a native amd64 codegen performance bug in MLton.  Typically, I expect that `pre codegen` time is about the same as `amd64 code gen time`, but on your `dimension-terms` branch, I see:
```
      pre codegen finished in 102.07 + 16.22 (14% GC)
      amd64 code gen finished in 622.28 + 20.92 (3% GC)
```
You could try compiling with `-codegen c` to avoid using the native codegen.

**Comment by jonsterling** [comment]
@MatthewFluet Thank you very much for the suggestion! With `-codegen c`, I get:

```
      pre codegen finished in 171.55 + 131.69 (43% GC)
      C code gen starting
      C code gen finished in 8.79 + 0.72 (8% GC)
   Compile SML finished in 180.39 + 132.41 (42% GC)
```

Now, it seems the bottleneck is compiling with `gcc` 😆 

I can probably stop the builds from getting killed on Travis by making them print out MLton's output as they go rather than just dumping it to a log (Travis kills a build after around 10 minutes of no output). I guess another sanity check which I could use instead of a full MLton build is just `mlton -stop tc`, and just only *test* with SML/NJ.

**Comment by favonia** [comment]
Another workaround is to use `travis_wait`.
