### ISSUE TITLE
unify all of RedPRL under sexpr notation (?)

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-redprl#395]
Having a uniform notation for all of RedPRL's sublanguages would be really nice; RedPRL-style sexprs seem a natural choice, because they are easy to parse and easy to print, and (excitingly) it is well-known how to provide excellent editor support for sexprs (e.g. paredit, etc.). Furthermore, it is probably one of the only notations which can be completely accurately highlighted in most editors without compiler-support.

There's a few questions that would need to be addressed:

1. How to differentiated between raw program terms and analogous tactics? For instance, right now we have program terms like `(lam [x] M)` and tactic expression `lam x. t`. One way to deal with the issue is to use different names for the operator, but this may get out of hand.

2. How to avoid tactic scripts getting too deep w/ parentheses; sometimes it can be stressful to edit a very deep point in a large sexpr... Sequential scripts that involve `fresh x -> ...` may become fairly gnarly, for instance. Perhaps this doesn't matter.

I'm sure there are other questions too. I wonder if @favonia has any thoughts about this.

I'm still not completely certain that we should do this; for instance, when we work on the new metalanguage (if that ever gets done), will we adopt a traditional ML-style notation, or will we use sexprs there?

**Comment by favonia** [comment]
For the first one, how about separately having `(intro [x y z] ...)` as the tactic?

**Comment by jonsterling** [comment]
@favonia That's not too  bad, I'm open to it.

**Comment by freebroccolo** [comment]
> How to differentiated between raw program terms and analogous tactics? For instance, right now we have program terms like `(lam [x] M)` and tactic expression `lam x. t`. One way to deal with the issue is to use different names for the operator, but this may get out of hand.

Couldn't you use some sort of special quasiquotation mechanism for this?

**Comment by jonsterling** [comment]
@freebroccolo 

> Couldn't you use some sort of special quasiquotation mechanism for this?

The idea makes sense, but there is an asymmetry between between those tactic-terms and the real terms—the former follow essentially the syntax of sequent calculus, whereas the latter are more like natural deduction. So, for introduction forms they basically coincide, but elimination forms tend to differ.

**Comment by jonsterling** [comment]
Here's some examples of what it might look like 

```lisp
(define (Identity [#l : lvl])
 (-> [ty : (U #l)] ty ty)
 (intros [ty x]
  (use x)))


(define (Monoid [#l : lvl])
 (U (++ #1))
  `(record
    [ob : (U #i)]
    [one : ob]
    [mul : (-> ob ob ob)]
    [idn/l : (-> [m : ob] (= ob ($ mul one m) m))]
    [idn/r : (-> [m : ob] (= ob ($ mul m one) m))]
    [assoc :
     (->
      [l m n : ob]
      (= ob
         ($ mul l ($ mul m n))
         ($ mul ($ mul m n) l)))]))


(define (Choice [#l:lvl)
  (->
   [a b : (U #i)]
   [r : (-> a b (U #i))]
   [f : (-> [x : a] (* [y : b] ($ r x y)))]
   (*
    [f : (-> a b)]
    (-> [x : a] ($ r x ($ f x)))))

  (intro [a b r f]
   (split
    [proj1 =>
     (intro [x]
      (case (f (use x))
       [(proj1 = y) => (use y)]))]
    [proj2 =>
     (intro [x]
      `(! (proj1 ($ f x))))])))

(define (QueryGoalType [#t : ([exp] tac)]) tac
 (query concl [goal]
  (match goal
   [ a | (true %a) => (#t %a)])))

(define MatchGoalExample
 (-> bool bool bool bool bool bool)
 (seq
  (repeat
   (QueryGoalType [ty]
    (match ty
      [a b | (-> [x:%a] (%b x))
       (seq
        (refine 'fun/intro)
        (fork id auto)))))
  [x y] (use y)))
```

I took a few liberties... It's a little hard to read, but not *too* horrible.

**Comment by favonia** [comment]
@jonsterling I think it's not too bad. I wonder how `(fresh ...)` should be written (which should apply to the cases in `(match)` as well).

**Comment by jonsterling** [comment]
@favonia I'm not sure about the `fresh` thing either. What I did in the example notation was that I made `seq` a binding form in its `n+1`th arguments (hence the `[x y]`), but it's a little ugly.

As for `match`, I think it is orthogonal, because `match` is its own binding for and doesn't use that `fresh` machinery.

**Comment by favonia** [comment]
What I meant is that
```(match goal [ a | (true %a) => (blah %a)])))```
can be thought as, in some sense,
```(match goal [a] (true a) [a] (blah a))```
and you can see that it has the same issue of `fresh` which talks about binding structures across subexpressions.

**Comment by jonsterling** [comment]
@favonia Ah, I'm still not sure I follow what you mean about binding across subexpressions; `fresh x -> t1; t2` could be written `(fresh t1 [x] t2)`, binding only in the second argument. The actual structure of `match` is that it takes a bunch of "clause" arguments, binding a bunch of pattern variables in each of them; a clause is formed by a pattern and a tactic, and the pattern variables is bound in the whole clause.

I'm not certain about the best concrete notation for match clauses; ideally we wouldn't even mention the names of the pattern variables, and would actually regard them in the notation as being bound "by" the pattern itself. I'm just not sure how to make that work.

**Comment by favonia** [comment]
@jonsterling Well, `fresh x -> t1; t2` can not be understood as `(fresh t1 [x] t2)` because, at least in the current implementation, `x` could potentially be used within `t1`. Does the new scope checker rule this out?

**Comment by jonsterling** [comment]
@favonia No, `x` cannot be used in `t1`; it is a syntax error to write, for instance, `fresh x -> use x; ...`. The operator in the abstract syntax that `fresh` corresponds to is actually `MTAC_SEQ`.

**Comment by favonia** [comment]
Actually, now thinking about it, given the number of people who have learned JavaScript (?!), perhaps `(lam [x] blah)` for both tactics and expressions are not so bad in practice after all?

**Comment by favonia** [comment]
Some food for inspiration: https://common-lisp.net/project/cl-monad-macros/monad-macros.htm
