### ISSUE TITLE
Use numbers directly instead of "projn"

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#406]
How about
```
{1 = blah, 2 = blah}
(! 1 foo)
```
instead of
```
{proj1 = blah, proj2 = blah}
(! proj1 foo)
```

**Comment by favonia** [comment]
Perhaps the difficulty is that we will at some point work within a context where the numbers become variable names... then it would conflict with the current overloading of numerals.

**Comment by jonsterling** [comment]
@favonia Yeah, I think that may be difficult to make work in the grammar; but I'm definitely open to choosing some shorter names than `projn`.

**Comment by jonsterling** [comment]
Actually, now that I think of it, it may be possible to make this idea work.

**Comment by favonia** [comment]
It should be possible after changing the numeral overloading. Do you have another idea?

**Comment by jonsterling** [comment]
@favonia I'd have to check, but I think at one point I had already changed the grammar of the record decomposition tactics, to the point where the record names are not used as variable names... I think you have to write like `lam {1 = x, 2 = y}. tac`, so there would not be an ambiguity there; this is the same as writing `lam {x, y}. tac`. As for the `!0` stuff, that wouldn't immediately work but we could make it work by changing the lexer.

**Comment by favonia** [comment]
@jonsterling Oh, then as far as I can see there's no issue then. We do not have to change the lexer. We can just have another rule
```
field_name = ident | NUMERAL
```
and encode the numeral back to a string. I think people would not mind even if "-000" becomes "0". (Is that even valid?)

**Comment by favonia** [comment]
Wait, I think the problem is still there---how should we define a record type (not a sigma type) using numerals to refer to previous components? Of course, we can just ban this.

**Comment by jonsterling** [comment]
@favonia Aha, I see what you mean 😆 

Yeah, while it is possible to just use the `(* [x : A] ...)` notation, I would like it to be still possible to use the more wordy `(record ...)` notation to achieve the same thing. So, we probably should not allow the field names to be numerals, unless we have in mind a sigil that can be used to distinguish them lexically. (And I am afraid we will run out of sigils very soon!)

**Comment by favonia** [comment]
Well, if we write integers as `(int 100)` then we can treat `100` as a valid variable name.

**Comment by jonsterling** [comment]
@favonia I'm not opposed to writing `(int 100)`, but I actually think it would be very confusing to allow numerals as variable names.

**Comment by favonia** [comment]
How about having `(! 1 a)` as a shortcut of `(! proj1 a)`?

**Comment by jonsterling** [comment]
@favonia Maybe this would work...

**Comment by jonsterling** [comment]
@favonia I thought about this some more and I think that the inconsistency in this latest proposal (the fact that `!` magically adds some text to the label) would make this more confusing than helpful. I would still like to come up with a notation that is less annoying than `projn` though, but I think as a design goal we should aim for the following:

1. `(! ...)` does not do any confusing syntactic sugar
2. It should always be possible to write the short form `(* [x : A] [y : (B x)])` explicitly using `record`.

**Comment by favonia** [comment]
@jonsterling How about `(# 1 blah)` expanding to `(! whateverprojwillbe1 blah)` then?

**Comment by jonsterling** [comment]
@favonia Ordinarily this would be a very good idea, but I think it is too confusing, since the `#` sigil is used to indicate metas.

**Comment by favonia** [comment]
Hmm, are these all the unused symbols? Or maybe we can consider `!#`.
```
~
"
'
,
&
^
< (after some PR)
> (after some PR)
|
\
/
+
```

**Comment by jonsterling** [comment]
Honestly I don't think that just finding another sigil is a great solution... In light of the fact that we're starting to pivot toward designing RedPRL to be easy to learn, I think that we should be trying to decrease the number of mysterious symbols that a user must grapple with, rather than add more of them.

And (maybe I'm wrong) but I am not sure I believe that it is a matter of priority to have a short notation for sigma projections. Part of the point of named records is that you can choose better and more informative names than `projn` for yourself! For instance, most of the HoTT-related things that are written with sigma types in the HoTT book would do very well to have named components.

**Comment by cangiuli** [comment]
If you use a sigma type with descriptively-named components, are you still able to use theorems about sigma types (without code duplication)?

**Comment by jonsterling** [comment]
@cangiuli Ahh, that's a good point. Not currently. So that's a good argument for not using named records...
