### ISSUE TITLE
Options to switch the dynamics

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#410]
I believe we have two implementations of the fcom types. What is the best way to try two implementations of their Kan operations?

**Comment by jonsterling** [comment]
Hmmm... Do you mean that there are two different versions of the dynamics in the notes, and we want to try and implement both?

I guess for now, you could add a flag to the machine (kind of like `STABLE | NOMINAL` or whatever we have now) if you wanted to try both...

**Comment by cangiuli** [comment]
Favonia has developed a second one; we don't plan on putting it in the main note. The problem is that different theorems will be true across the two versions of the operational semantics.

**Comment by jonsterling** [comment]
Ahh, interesting! Then I would suggest adding another parameter to the machine, unless you have a better idea.

**Comment by favonia** [comment]
@jonsterling How to make it accessible to the user, then? A compiler flag?

**Comment by jonsterling** [comment]
I guess we could expose it with a flag on the frontend...

**Comment by cangiuli** [comment]
Language pragmas? (Not totally joking...)
