### ISSUE TITLE
Relaxed stability?

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#417]
@cangiuli @jonsterling I want to say the dynamics associated with ``(coe y~>r [x] (V x ....) ...)`` is stable after taking the transitive closure. It is like the bisimulation stuff or the generalized coherent head expansion lemma. This way we can claim that asserting `y` is a variable does not destroy stability even if `y` is not bound.

**Comment by cangiuli** [comment]
@favonia Isn't this actually entirely obsolete with the modified dynamics? (I am proposing removing C-wont-fix-for-now.)

**Comment by favonia** [comment]
Not really. This is actually trying to generalize those unstable beta rules to something potentially more immortal. Hopefully this will become obsolete in the presence of immortal proof theory.
