### ISSUE TITLE
Add line types to internalize (#i:dim)

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#418]
@cangiuli How about line types, which recognize `(abs ...)` as values but do not specify their end points? Path are subtypes of lines. (Better names are welcomed.)

**Comment by cangiuli** [comment]
I approve. Unfortunately `Path` would be a good name, as it is a path space. How about `P(x.A)` -- would you prefer something more descriptive?

**Comment by jonsterling** [comment]
@cangiuli I don't want to use anything mysterious/ugly like `P(x.a)` in RedPRL, but you can use whatever you want in the paper... Actually, in RedPRL we could even pun the word `path` for both.

Another option would be to call it `line`, as Favonia has suggested.

**Comment by cangiuli** [comment]
Evan and I have synthesized our Thoughts and present the following suggestion: `(x dim) -> A` where `x` is bound in `A`.

**Comment by cangiuli** [comment]
Allowing `path` to have two different arities seems kind of confusing to me, especially because we don't need to give them the same Kan operation. @favonia: any thoughts about the Kan operation?

**Comment by favonia** [comment]
Hmm it seems
```
(coe r~>r' [x] (line [y] a) m)
```
should be
```
(abs [z] (coe r~>r' [x] a (m @ z)))
```
but I have to sit down and work on its hcom.

**Comment by favonia** [comment]
@cangiuli its hcom should also mimic the pi types as it's coe.

**Comment by cangiuli** [comment]
I meant that we could give line types the same Kan operations as path types; this would be more complicated but might be useful if you pass between the two types often, I don't know.

**Comment by favonia** [comment]
Where did the proof we have done yesterday go?

**Comment by cangiuli** [comment]
It's on the examples branch, 291ecc043af9bbec5342237eef7c2033d628575b.

**Comment by favonia** [comment]
@jonsterling Is there any reasonable semantics for `(* [a:dim] A)`? That is, the Sigma-type version of `(a:dim) -> A`?

**Comment by cangiuli** [comment]
I don't think so. (Well, if we had a strict interval type then it would be a sigma over that, I guess.)

**Comment by ecavallo** [comment]
@favonia `(* [a:dim] A)` will be implementable as a cubical inductive type: it has one 1-dimensional constructor with no specified boundary.
