### ISSUE TITLE
POPL 2018 tutorial

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#425]
@cangiuli @jonsterling What should be done? How about creating a milestone to tag all the issues which must be fixed before POPL 2018?

**Comment by jonsterling** [comment]
Great idea! 👍

**Comment by jonsterling** [comment]
This will serve as a good forcing function.

**Comment by jonsterling** [comment]
(Oops, didn't mean to close. sorry!)

**Comment by favonia** [comment]
@cangiuli @jonsterling What are the main things we need to address but have not created issues for?

**Comment by favonia** [comment]
@cangiuli @jonsterling @RobertHarper What should be the top priority for RedPRL-hacking now?

**Comment by cangiuli** [comment]
For the POPL tutorial I can work around whatever we have, but:

- it would make a great demo if Omega_1(S^1) works, or at least we can compute winding numbers.
- I really want support for line types in `auto`, since they're unusable at the moment.

**Comment by favonia** [comment]
The function to compute winding numbers is already there.
