### ISSUE TITLE
Make error messages flow.

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#432]
Should we include a primitive like `textflow` such that `textflow "hello world"` would be turned into `hvsep [text "hello", text "world"]`?

**Comment by favonia** [comment]
Actually, `hvsep` is not what I want, because it either does space or newline at all positions.

**Comment by jonsterling** [comment]
@favonia Can you explain what the intended use-case of this would be? If it sounds like something we need, then we can implement it in https://github.com/RedPRL/sml-final-pretty-printer

**Comment by favonia** [comment]
One example is that maybe the library can intelligently choose one of the following formats:
```
The term (blah blah blah) is not recognized by the kitten
for the type (blah blah blah).
```
and
```
The term
 (blah blah blah
  (blah blah blah))
is not recognized by the kitten for the type
 (blah blah blah blah
  blah (blah blah)
  (blah blah)).
```

**Comment by jonsterling** [comment]
I think there is already a way to achieve this smart choice, but I can’t remember exactly how.

**Comment by favonia** [comment]
@jonsterling If possible, I do not really want to specify the breaking points in a string "is not recognized by the kitten for the type" but leave them to the renderer. The marking of breaking points should probably be done in RedPRL because it is language-specific, but the algorithm to decide where exactly the breaking is happening could be in the library.

**Comment by favonia** [comment]
The `hov` box in OCaml's `Format` is one step closer to what I want.
