### ISSUE TITLE
Have semantics of MATCH defined in terms of values?

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#441]
@jonsterling How about defining the semantics of MATCH asd MATCH_RECORD from only values so that we can fearlessly implement auto-reduction and aute-unfolding?

**Comment by jonsterling** [comment]
@favonia Can you give a bit more details on what you have in mind?

**Comment by favonia** [comment]
@jonsterling I want to repurpose `MATCH` as "evaluating the argument to some value, and matching the pattern against that value". I believe the current usage fits into this new definition.

**Comment by jonsterling** [comment]
@favonia I think that makes a lot of sense. Do you think that it is semantically correct? (It seems correct, just wanted to check.)

**Comment by favonia** [comment]
@jonsterling There are no correct or incorrect _definitions_ (with respect to the semantics). Perhaps you were asking whether we can add evaluation everywhere? I believe all current rules are using `MATCH` under the assumption that the targeted term is a value (or the matching would fail).

**Comment by jonsterling** [comment]
Thank you, I think you are right! I think your proposed change will help a lot.
