### ISSUE TITLE
Error messages for arity mismatch of custom operators

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#442]
I think it is a bug that RedPRL is silently ignoring the extra parameters.

**Comment by jonsterling** [comment]
Yes, I think this is a bug.

**Comment by jonsterling** [comment]
I think the error must be in `tactic_elaborator.fun`.

**Comment by jonsterling** [comment]
Or maybe in `Signature`, depending on exactly which bug you are referring to... I think there may be a couple issues.

**Comment by jonsterling** [comment]
I've found the source of the bug, will fix shortly.
