### ISSUE TITLE
Better messages explaining why a particular auto-step fails

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#448]
Right now, if an auto-step fails, it's basically a mystery to inexperienced users. Maybe some suggestion to run "refine foo"?

**Comment by jonsterling** [comment]
Good thought! Though it may be harder to give good messages here than it is to just improve auto (and get rid of auto-step).

At the very least, we should improve what we have, since often the error message you get is something stupid like "nonexhaustive match" or something ridiculous like that.

**Comment by favonia** [comment]
One related issue is that I do not feel the logging system is doing its job now.

**Comment by favonia** [comment]
@jonsterling What did you mean by getting rid of `auto-step`? Did you mean something like #438? (I believe #438 is compatible with `auto-step`, though.)

**Comment by jonsterling** [comment]
@favonia It may be possible to implement #438 and retain auto-step, but I think that long-term this stateless, small-step approach to automation is not going to serve us as well as I had hoped. My thinking is that to have a good proof search algorithm, we kind of need to keep track of what we're doing across multiple steps; but maybe I'm wrong.

I was imagining that the "ultimate" version of `auto` might be some kind of function that you could give a possibly infinite (but possibly finite) amount of 'fuel' to. Anyway, I'm not sure about it.
