### ISSUE TITLE
Flag to adjust linewidth of redprl printout

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-redprl#449]
This is important for when the term is too big, and you end up with like 1000 lines of silly five-character spurts.

@cangiuli

**Comment by cangiuli** [comment]
This would be really great to have for vim-redprl, because I could pass in the actual width of the RedPRL buffer!

**Comment by jonsterling** [comment]
@cangiuli whoa, that's a great idea!

**Comment by cangiuli** [comment]
I'm going to begin swimming among the RedPRL source files, and this seems like a good place for me to start.

**Comment by cangiuli** [comment]
Fixed by #514.
