### ISSUE TITLE
Notation of equality types

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#450]
After #351, perhaps we can rethink the notation of equality types. I have been constantly trapped by `(= ty m n)` because we write `m = n in ty` for judgments, but if equality judgments are gone, perhaps this will no longer be an issue? @cangiuli What would you prefer, under the blessings of the god of S-expressions?

**Comment by cangiuli** [comment]
I actually think `(= ty m n)` makes more sense in the abstract, and my LaTeX macros take the same argument order, but when juxtaposed with the judgments it's not very intuitive.

Ddo you think we can get rid of equality judgments altogether?

**Comment by favonia** [comment]
I guess so. So it seems everything would be fine once #351 is done? I am closing this then. Feel free to re-open it.

**Comment by favonia** [comment]
@cangiuli Wait, how about the unary notation? How would you like to abbreviate `(= ty a a)`?

**Comment by cangiuli** [comment]
I guess just `(= ty a)`? Neither solution seems perfect.

**Comment by jonsterling** [comment]
@cangiuli I think that's a bit too confusing, since in many systems you abbreviate `M = N in A` with `M = N`.... Maybe we could name the operator `mem` or `in`, and then the only confusing part will be to choose what order to put the arguments.

**Comment by favonia** [comment]
Or... `(ni ty a)`

**Comment by jonsterling** [comment]
@favonia *We are the knights who say "\ni"!*

**Comment by favonia** [comment]
@cangiuli Any objection to (ni ty a)? @jonsterling Is that another slogan? Did you see the idea about "we march for computation"?

**Comment by jonsterling** [comment]
@favonia I love your computation slogan! Another good one would be *“Dare to compute!”*
