### ISSUE TITLE
Less confusing tactic notation

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-redprl#454]
[This is related to #422.]

There are two problems with RedPRL's tactic script notations: first, they are not documented; second, they are very confusing and non-consistent, and unintuitive to new users. I am reluctant to fix the first issue before fixing the second one.

One area of confusion is the difference between `.` and `;`. The dot is really just part of the notation for a single tactic-former, whereas `;` is a tactical that combines tactic expressions, just like in Coq. One way that we might avoid confusion is if we used a different delimiter than `.` for the scopes; for instance, we could write `abs x... => t` and `lam p... => t`, where `p` is a decomposition pattern and `X...` indicates multiple instances of the production `X` separated by commas.

Another issue of confusion is these brackets; for instance, we use square brackets to make something analogous to `THENL` from LCF (what Coq writes with `t; [t1 | t2 | ...]`). But we also use square brackets for the list of identifiers after `unfold`, which we needed for getting rid of ambiguity, but which is also confusing. I'm not sure how to resolve that.

I'd like to come up with a new grammar for tactics that is readable and parsable, and implement it. I think this may be important enough to prioritize, since it's now no longer the case that @favonia and @jonsterling are the only ones writing RedPRL code.

@cangiuli @mortberg

**Comment by jonsterling** [comment]
Another area of confusion is the notation for let-bindings *qua* sequent calculus left-rule vs let-bindings *qua* cut. I'm not sure of the best notations for these, but what we have right now is very unintuitive.

**Comment by favonia** [comment]
You know I am a big fan of turning everything into an S-expression and eventually using the ML you are developing.

**Comment by jonsterling** [comment]
@favonia Yeah... I wish we could skip to that right now 😆

**Comment by favonia** [comment]
Which one are you skipping to? S-expressions? ML?

**Comment by jonsterling** [comment]
@favonia Well, both 😄

**Comment by cangiuli** [comment]
To be honest, while I agree the syntax can be improved, it's not a big source of confusion. I am having a much harder time just knowing what tactics exist, and why particular subgoals don't go away.

**Comment by jonsterling** [comment]
@cangiuli OK; so maybe what we should do is document what tactics exist, as a first step.

As for the last problem (why do particular subgoals not go away) we can't really *ever* fix that properly (but improvements along the lines of #438 and #448 can help mitigate)—or at least, this was something that they were never able to address in Nuprl, but we can hopefully do better than we are doing now (which is pretty bad).

**Comment by favonia** [comment]
@cangiuli So far I see #450. What would be the other parts that confused you? Does something like http://eblong.com/zarf/pic/play-if-card.png help? It boils down to polishing this list: https://github.com/RedPRL/sml-redprl/blob/a6f2a805f0a87c506c29975185b0645c271665c2/src/redprl/refiner.fun#L349-L415

**Comment by cangiuli** [comment]
@jonsterling I understand that we can't solve this problem perfectly, but I think the things I've complained about are extremely reasonable expectations for `auto`. :wink: 

@favonia While it helps to know what the rule tactics are called, I'm getting more stuck on things like not knowing that `let` existed, and what square brackets mean. If we're about to change everything then now is not the time to write documentation, of course.

**Comment by jonsterling** [comment]
> I understand that we can't solve this problem perfectly, but I think the things I've complained about are extremely reasonable expectations for `auto`

It may seem like this to you as a user, but please know that in the real world it is actually very non-trivial to achieve even these 'reasonable expectations'. What are 'reasonable expectations' tend to be adjusted as one begins to understand the bleak reality of implementing a system that can't have a typechecker.

What that said, we can continue to make improvements, and it's likely that we can address all the problems we've seen so far. **What I'm trying to express, though, is that this is a game of whack-a-mole: each thing we fix may lead to other problems elsewhere, which is why 'reasonable expectations' are dangerous.**

The reality is, I think the principal problem is that it is confusing why some things don't work immediately and yet other things *do*; for instance, as we discussed yesterday, it's surprising that some very gnarly `hcom` can go through with no problem, but something very easy does not. Because there is no general story for this, we can only hope to reduce the frequency of such confusion.

**Comment by favonia** [comment]
@cangiuli (Responding to your response to my parts only.) Basic grammar should be covered by that cheat-sheet as well. What I mean is handing out postcard-like cheat sheets to students, and I wonder if someone at CMU can help?

**Comment by favonia** [comment]
Can we close this now?

**Comment by favonia** [comment]
By the way, I noticed that the `.` for binding tactics has been universally replaced by `;`. Is that intentional? If so, maybe we can restore `.` for `lam a.`.

**Comment by jonsterling** [comment]
There was some discussion and basically everybody except me hated the dot and preferred the semicolon; so we switched it.

**Comment by favonia** [comment]
In that discussion, does everyone else hate `lam a.` and `abs i.` as well?

**Comment by jonsterling** [comment]
@favonia Yes, they hated that too; we switched to the semicolon for everything, iirc.

**Comment by favonia** [comment]
Not really, I think it is still `lam a =>` and `abs i =>`.

**Comment by jonsterling** [comment]
@favonia Oh, you're right; I forgot. Yes, we changed to a combination of semicolons and arrows, depending on what seemed to make the most sense.

**Comment by jonsterling** [comment]
I think btw that we can close this issue if there are no objections; of course, we can open further tickets for specific confusing notation.

**Comment by cangiuli** [comment]
I have no objections.
