### ISSUE TITLE
Tactic cheat sheets

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#455]
This is a spin-off thread from #454. Let's (find someone to) make something like this: http://pr-if.org/doc/play-if-card/play-if-card.pdf

With inspiring slogans, red stars and floating lambdas, of course.

**Comment by jonsterling** [comment]
I love this idea! Great thinking, @favonia.

**Comment by cangiuli** [comment]
Does this cheat sheet include the order of the subgoals generated?

**Comment by jonsterling** [comment]
That'd be very helpful, though ideally this is not something users should need to know about (since using low-level rules should be as rare as possible.) Sadly today, it is helpful to know it.
