### ISSUE TITLE
Goals are impossible to read / too noisy

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-redprl#459]
A lot of auxiliary hypotheses get generated (for instance, when you use repeated `n`-ary function eliminations!), but this makes everything really impossible to read.  We should have some way to filter out the garbage from the sequent.

**Comment by favonia** [comment]
Eventually we need https://d3js.org/ and https://webvr.info/, right? But before the doomsday perhaps we can extend the `?` syntax to do something fancier.

**Comment by jonsterling** [comment]
@favonia haha, that would be so sweet!!

But yes, in the meanwhile we can maybe provide some various filtering schemes, and let users select these with that `?` thing.

**Comment by cangiuli** [comment]
Closed by #549, funnily enough.
