### ISSUE TITLE
Rules for rewriting types

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#465]
Rules for rewriting types enjoy a special property that functionality always holds. The usual rewrite rules are next to impossible to rewrite types in the real application. Already discussed in private emails, it seems there is no obvious way to generalize this, and so let's implement this special rule after #457 but before #383. This probably also needs syntactical support in #404.

**Comment by favonia** [comment]
@cangiuli @jonsterling When the conclusion is an equality judgment `m = n in a`, and you say `rewrite eq in concl`, what would you expect to happen? Which part should be rewritten?

**Comment by favonia** [comment]
Proposed design for the rewrite tactics:
```
a = b type
rewrite eq at left
rewrite eq at right

m = n in a
rewrite eq at left
rewrite eq at right
rewrite eq at type

a true
rewrite eq
(?) rewrite eq at type
```

**Comment by jonsterling** [comment]
@favonia I like your design. Re: if we have something like `in concl`, I would expect it to apply to the entire conclusion.

**Comment by favonia** [comment]
> if we have something like in concl, I would expect it to apply to the entire conclusion.

Well, we need both `rewrite blah at position in x` and `rewrite blah at position in concl`. `in` is to pick the atomic judgment, and `at` is to specify the part. Maybe some native speaker (you) should step in and come up with something less confusing.

**Comment by favonia** [comment]
Sorry I made a mistake. The current parser will already fill in `in concl` for you if `in` is missing. So at least there's some natural way to rewrite the conclusion. However, to rewrite a hypothesis, it seems we need two prepositions. I picked `in` and `at` arbitrarily.

**Comment by jonsterling** [comment]
I think `in` and `at` are the right prepositions
