### ISSUE TITLE
Make a new folder for examples

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#477]
Files under `test/` should be simple (unless such complexity is necessary for testing some functionality). Univalence, pi1(S1), semi-simplicial types, etc do not belong there. @cangiuli

**Comment by favonia** [comment]
High priority due to paper publishing.

**Comment by jonsterling** [comment]
Yes, I agree. We should have a folder called `examples/` or something that is separate from tests; and we can still have these be run automatically by Travis to be sure we don't break anything.
