### ISSUE TITLE
Allows only TRUE in THM?

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#481]
@jonsterling

**Comment by jonsterling** [comment]
@favonia Can you explain what you mean or propose?

**Comment by favonia** [comment]
Users can only prove `TRUE` judgments in `THM`.

**Comment by jonsterling** [comment]
@favonia Oh, then I'm ok with that idea.

**Comment by favonia** [comment]
Actually, I don't care about this anymore. I wanted this because of the special level assignment needed by #466. Feel free to reopen this.

**Comment by jonsterling** [comment]
Ok! Eventually it will get done as a side effect of other tasks, but we don’t need to track it.
