### ISSUE TITLE
rec creates unusable mtac variable

### ISSUE THREAD

**Issue by ecavallo** [RedPRL/sml-redprl#507]
The multitactic `rec` introduces a variable of sort `mtac`, but there is no clause in the parser for `mtac` variables, so if you use the variable it will be parsed as a tactic (that is to say, it will be wrapped in an `MTAC_ALL`). For example,
```
Tac Omega =
[
  rec u => {u}
].
```
fails to parse with `Sort Error: expected mtac, but got tac`. Not sure how to fix this without introducing notation to label uses of `mtac` variables.

**Comment by jonsterling** [comment]
you're right! We ought to fix this... It never got noticed because nobody really has used this tactical in practice.
