### ISSUE TITLE
Add new kinds for regular types

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#508]
Time to make RedPRL an 8-level type theory, following the Fibonacci numbers. (The RedPRL in Part 3 has 3 levels, the current RedPRL has 5 levels, and then...)

**Comment by favonia** [comment]
@cangiuli @ecavallo I feel adding a new kind of regular types is completely useless. Do you have any example of a regular type which is _not_ discrete? Right now, discrete types have better closure properties than regular types and I could not find an interesting example which is regular but not discrete.

**Comment by cangiuli** [comment]
The circle is coe-regular and not discrete... But yes, @ecavallo and I aren't sure how useful the regular types would be. Maybe it would be best to close until we have a reason to want them.

**Comment by favonia** [comment]
Closed as there are no interesting examples.
