### ISSUE TITLE
Compile / serialize elaborated signatures

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-redprl#51]
This gives us a way to save some work—imagine being able to take an already-elaborated signature (such as one from a file) and add a new declaration to it; elaborating the result of this will only incur the cost of elaborating the new definition, since all the old stuff will be skipped.

This gives us a plausible way to have a real notebook-style interface, where the output of each "cell" is just an elaborated signature—allowing us to elaborate developments incrementally rather than repeatedly.

**Comment by jonsterling** [comment]
This is becoming absolutely crucial, as RedPRL becomes too slow to operate in the mode of "recheck everything with every keystroke".

@cangiuli

**Comment by favonia** [comment]
While I believe the importance of this feature (crucial for #353, for example), I suggest some profiling before allocating our time to a particular part.

**Comment by jonsterling** [comment]
@favonia Agreed.
