### ISSUE TITLE
Labels are leaked as confusing variable names (without underscores) in contexts without explicit `fresh ->`.

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#513]
Not sure if this is intended or a bug.

**Comment by jonsterling** [comment]
It sounds like a bug, but it's hard to tell... Can you point out where this is happening?

**Comment by favonia** [comment]
https://github.com/RedPRL/sml-redprl/blob/1d90695f5ab9ebbff70f8263a722aac34be758c9/src/redprl/refiner_types.fun#L957-L958

**Comment by jonsterling** [comment]
@favonia Yes, it sounds like a bug. It will be a little tricky to fix it, but we can do it.

Ultimately I want to figure out a better approach for names... I'm just not sure of what it would be.

**Comment by cangiuli** [comment]
See also https://github.com/RedPRL/sml-redprl/issues/542.
