### ISSUE TITLE
Consider having EQ_TYPE synthesize something of sort exp.

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#530]
Now with `EQ` internalized as `TRUE`, we have to painfully handle the discrepancy between `AX` and `TV` when trying to write uniform code for `EQ`/`EQ_TYPE`. Things would be easier if a realizer of an `EQ_TYPE` judgment actually has sort `EXP`, or we give up `TRV` entirely.

**Comment by jonsterling** [comment]
Might as well!
