### ISSUE TITLE
Add command-line option for printing traces?

### ISSUE THREAD

**Issue by cangiuli** [RedPRL/sml-redprl#538]
At the moment, traces are printed as a part of proof states. I propose adding a command-line flag (maybe `--debug` or `--trace`) to enable this, and having them off by default. I would then also expose a switch to enable this in the vim mode. The reason is that the trace adds noise and isn't particularly helpful to those who aren't familiar with the internals.

cc @favonia

**Comment by jonsterling** [comment]
It sounds reasonable; I think that `--trace` makes sense as the name of the flag. 

@cangiuli What kind of interface did you have in mind for the vim mode?

**Comment by cangiuli** [comment]
For now, just the ability to write `let g:redprl_trace = 1` in your `.vimrc` (or just run that command whenever you need it) to turn on tracing.

**Comment by jonsterling** [comment]
@cangiuli Hmmm... I guess that would work!
