### ISSUE TITLE
Assign names after the introduction of variables.

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#542]
I think I would prefer pushing names after the tactic. What it means is that
```
fresh n ih -> elim n,
[ zeroCase
, succCase
]
```
is replaced by something like
```
elim n,
[ zeroCase
, n ih => succCase
]
```
The names, `n` and `ih` were assigned just before the tactic. The use of `=>` has the extra bonus that
```
lam x => body
abs i => body
```
are really nothing special except there's no comma (and maybe scoping? not sure).

(EDIT: delete the `lam body` because `lam` actually takes a variant number of variables.)

**Comment by jonsterling** [comment]
That'd be awsome! I think it's not actually possible to do with the current model of name stores, but what we have is so screwed up generally that I want to replace it anyway.

We should keep this in mind as a design goal when we replace it.

**Comment by favonia** [comment]
By the way, for the elimination rule of integers, this would be
```
elim n,
[ zeroCase
, n ih => succCase
, negOneCase
, n ih => negSuccSuccCase
]
```
for some reasons I actually prefer duplication of these local assignments. The implementation details (how names are used across branches) should not be exposed to users. Also, I hope each tactic "resets" the list of pending variables so that, for example,
```
elim n,
[ zeroCase
, n => succCase
, negOneCase
, n => negSuccSuccCase
]
```
should work as if the inductive hypotheses are not named. This makes sure the `blah` in
```
elim n,
[ ...
, elim m
  [ ...
  , m => blah
  ]
]
```
will not interact with the outside `elim n`. The "downside" is that, if any `elim` or other tactics using names are called in `auto`, the newly hypotheses are unnamed forever. This would force the user to write out all the tactics/rules if they want to name anything. I actually prefer this as this seems to prevent unstable proofs relying on what exactly `auto` does.

**Comment by jonsterling** [comment]
>  I actually prefer this as this seems to prevent unstable proofs relying on what exactly auto does.

This is very interesting, and I think you may right. In fact, ultimately I feel that we should only expose a version of `auto` that either completely succeeds, or completely fails (or diverges, lol). Like Coq and Nuprl's `auto`. I think it is *always* bad proof engineering to run `auto` and then continue scripting where `auto` left off.

It may mean that certain proofs get a bit longer, but they will have more structure and will be more stable.

**Comment by jonsterling** [comment]
@favonia I now have an immortal idea for how to achieve this ticket! Simultaneously, we can get rid of the horrific propagation of `alpha` throughout the rules.

**Comment by jonsterling** [comment]
[My Thought is based on my experience using the `ssreflect` plugin in Coq. I think that sequents should have two contexts: one "global" context, which contains the variables that are nameable by the user; one "local" context which contains the variables which are not nameable to the user. All rules that add hypotheses will add them to the local context.

Here's where it gets interesting: the local context is like a stack, and the user can push and pop things from it. When the user pushes a variable onto the local context from the global context, the variable is freshly renamed and can no longer be accessed by the user. When they pop a variable from the local context, the user has to chose a name for it, and then the rest of the sequent is renamed accordingly.

The `elim` example of Favonia would be captured perfectly by this concept: 

```
elim n,
[ zeroCase
, pop n => succCase
, negOneCase
, pop n => negSuccSuccCase
]
```

The sweet thing about this approach is it means that there is now never any such thing as a "lost" name (one which the user can never get their hands on).

**Comment by favonia** [comment]
Sounds cool. I would like to know more about the interaction between tactics. How should the following example translate?
```
elim n,
[ ...
, elim m
  [ ...
  , m => blah
  ]
]
```

**Comment by jonsterling** [comment]
@favonia is it intentional in your example that you shadow `m`?

**Comment by favonia** [comment]
Not really intentional, but I think it is natural to recycle variable names during pattern matching.

**Comment by favonia** [comment]
I believe what's done in #570 differs from what I proposed here in that (1) the stacks here are local and (2) the order is in reverse (that is, it is really a FIFO that will be reset every time). Yes, the unnamed will be lost forever after the following rule, and that is intentional in my proposal. I was trying to localize the effects of each rule. Is there a reason to adopt the approach in #570? On the contrary, several underscores in the examples can be omitted if they are FIFOs.

**Comment by jonsterling** [comment]
@favonia I thought about it some, and I actually believe now that it is important that users always be able to recover names, contrary to the proposal here which is that names should only be accessible immediately after the rule that caused them to come into being.

Your point about `auto` (re: being able to use names that are generated from deep in `auto`) is well-taken, but generally it may not hold for other tacticals that the user chooses to develop, or that we may include.

**Comment by favonia** [comment]
@cangiuli @jonsterling I see the issue of composition. Here is a more refined approach. The idea is to have two queues: one for "immediate use" and the other for "after-scope use". In my imagination the dynamics of the fragment without choices would be something like the following. Do you think this would work?
```
tac1 : (l0, m0) -> (l1, m1)
tac2 : (l1, m1) -> (l2, m2)
------------------------------------------------
tac1, tac2 : (l0, m0) -> (l2, m2)

------------------------------
id : (l0, m0) -> ([], m0)

tac : (l0, []) -> (l1, m1)
---------------------------------------------------
vars => tac : (vars ++ l0, m0) -> (l1, m1)

tac : ([], []) -> (l1, m1)
---------------------------------------------------
{tac} : (l0, m0) -> (l1, m0 ++ m1)

```

**Comment by jonsterling** [comment]
@favonia I am not certain, but I think that even this one would be fairly disruptive... Can you elaborate a bit more on why you want this?

**Comment by favonia** [comment]
Because I want to (1) ban all the fragile proofs that pop out names from unknown tactics which may suddenly be broken if we change something, and (2) allow the proof to be resistant to potential changes to the auxiliary hypotheses. The first point needs locality, and the second point wants queues instead of stacks.

**Comment by favonia** [comment]
The main point (point (1)) is to ensure that names follow some principles based on lexical scopes. Point (2) is really a bonus after point (1).

**Comment by jonsterling** [comment]
> Because I want to (1) ban all the fragile proofs that pop out names from unknown tactics which may suddenly be broken if we change something

The problem is that we basically can't do this, unless I misunderstand what you mean (I also had a hard time understanding your operational rules, so I may not be fully grasping your idea). The reason it seems like we can't do this is that I don't know a way to distinguish between non-local names that you *shouldn't* be allowed to access, and those which you *should*.

Sure, one can argue that you shouldn't be able to see the names that pop out of `auto` or something. On the other hand, if I write `elim x; elim y;...` I **should** be able to pop the names that came from these tactics all at once. This is a contrived example, but generally the idea is absolutely *crucial* for composition.

The problem with `auto` would be resolved not by imposing an anti-compositional notion of name source, but rather by making it so that `auto` behaves like it does in Coq and Nuprl: where it never emits an intermediate state, and either succeeds or doesn't do anything. I believe that this is the way to address the issue of fragile proofs. When `auto` doesn't completely discharge its goal users should be forced to write a more structured proof. Indeed, the problem with fragility is not only derived from the weird names that users can access, but in fact also because of the fact that the intermediate proof states that users are touching are not stable under small changes to the `auto` tactic.

**Comment by jonsterling** [comment]
And for (1), the proposal that i have implemented *does* ensure that names follow some kind of lexical scope: this is ensured by the binding structure of the tactical `pop x... => tac`. The atomic `pop x` operation is *not* exposed in the tactic language, so everything is ensured to be balanced; `pop x => tac` is semantically `pop x; tac; push x`.

**Comment by favonia** [comment]
> The problem is that we basically can't do this, unless I misunderstand what you mean (I also had a hard time understanding your operational rules, so I may not be fully grasping your idea). The reason it seems like we can't do this is that I don't know a way to distinguish between non-local names that you shouldn't be allowed to access, and those which you should.

The two lists can be part of a goal or a telescope.
 
> Sure, one can argue that you shouldn't be able to see the names that pop out of auto or something. On the other hand, if I write elim x; elim y;... I should be able to pop the names that came from these tactics all at once. This is a contrived example, but generally the idea is absolutely crucial for composition.

This can be achieved by `{elim x; elim y}; [x y => blah, ...]`. The scope `{...}` tells you how far the composition should go, and it can be layered. Did you find the syntax acceptable? On the other hand, `tac; => id` will stop any variable from leaking. By scoping I was talking about `{}` and the principle in question is between tactics and the variables they generate.

**Comment by favonia** [comment]
Following this idea, `repeat tac` (equivalent to `{{tac; repeat tac} || id}`) will collect all the residual names from each run of `tac`. I hope these cover all forms of composition in your mind.

**Comment by jonsterling** [comment]
@favonia I think I see what you mean, but I don't know if I like it. It looks like it would make it very very difficult to write general purpose tacticals (I'm convinced that it is *possible*, but that it seems like it would be far more bureaucratic), without much benefit in return---to be clear, I do see the benefit of what you say, but it seems marginal in comparison to the increase in complexity. In particular, how do you intend to give a user interface to this?

For the simple version I have implemented, we don't really need any special user interface. Carlo proposed that these variables should get some names like `_0, _1` depending on their position in the stack. Pushing and popping is not so different from using `ssreflect`, so it will be familiar to many users. On the other hand, this scheme with two different places for variables might make some sense to us, but I am concerned that it is too complicated to explain, and that the benefit it provides is not very convincing (yet).


I would like to have something very simple that works in the general case.

@cangiuli What do you think?

**Comment by cangiuli** [comment]
I don't think our scheme is that confusing: the idea is that unnamed variables are given inaccessible names `_0`, `_1`... and you can name them with `pop x =>` going from newest to oldest.

I'm also a bit worried about general-purpose tacticals in Favonia's setting, and I'm not sure I understand the objection, given that we also want to prevent users from accessing the result of an incomplete `auto`. If the user doesn't know what tactic was applied last, then names aren't the only problem -- they also don't know what the subgoals look like, etc.

**Comment by favonia** [comment]
@jonsterling The syntax would be similar to what is done in #570. I did not propose adding any other new tacticals.

@cangiuli I'd like to clarify that my objection is not just preventing access to the internal of `auto`. Consider the tactic script
```
tac0; tac1; tac2; pop _ _ _ _ _ x y z w => blah; pop _ _ _ _ _ i => foo
```
I hope I can edit `tac1` without worrying about the rest of the script. Right now the dependency is unbounded and I would have to count underscores in some situations. In sum, the proof is "fragile"---a local change could have some annoying non-local effects.

That said, whatever version it is, #570 is better than the status quo and we should merge it now. Just that I am not totally satisfied.

**Comment by jonsterling** [comment]
@favonia Thanks for your clarification... I think I see better what you are saying. I agree that somehow it is unsatisfying that we have no way of making code less fragile. It seems plausible that we might somehow add a primitive tactical that could provide some barrier, though I don't know how it would look in our setting.

We should continue to think about it, and hopefully we can find a way to address this issue that you raise. In the meanwhile, I suggest that I should fix the remaining issues in #570 (mostly UI issues).

**Comment by favonia** [comment]
If you are going to implement some barrier, I strongly recommend the semantics outlined in the above comment. Adding two lists is not more difficult than adding one (of accessible variables).

**Comment by favonia** [comment]
Let me show the proof script in the alternative implementation. This is one proof that I really want to ban/rewrite:
```
Thm Thm3/low-level : [
  (->
   [p q r : (U 0)]
   (-> p q)
   (-> q r)
   (-> p r))
] by [
  // fresh p q r pq qr x -> 
  repeat {refine fun/intro || id};
  auto; pop x qr pq r q p => 
  elim qr; elim pq;
  [ use x
  , pop _ y => use y
  , use x
  , pop _ _ _ z => use z
  ]
].
```
This would become the following under the new semantics:
```
Thm Thm3/low-level : [
  (->
   [p q r : (U 0)]
   (-> p q)
   (-> q r)
   (-> p r))
] by [
  {repeat {refine fun/intro || id}; auto};
  p q r pq qr x =>
  elim qr; z =>
  elim pq; y =>
  [ use x
  , use y
  , use x
  , use z
  ]
].
```
or
```
Thm Thm3/low-level : [
  (->
   [p q r : (U 0)]
   (-> p q)
   (-> q r)
   (-> p r))
] by [
  {repeat {refine fun/intro || id}; auto};
  p q r pq qr x =>
  {elim qr; elim pq};
  [ use x
  , _ _ y => use y
  , use x
  , z => use z
  ]
].
```
