### ISSUE TITLE
Don't print internal metavariable names

### ISSUE THREAD

**Issue by cangiuli** [RedPRL/sml-redprl#547]
The following code:
```
Thm Not : [
  (-> bool bool)
] by [
  lam b =>
  if b then `ff else `tt
].

Thm NotNot : [
  (->
   [b : bool]
   (= bool ($ Not ($ Not b)) b))
] by [
  lam b =>
  // The next two lines can be replaced by auto.
  unfold Not;
  if b then (reduce at left; refine bool/eq/tt) else (?)
].

Print NotNot.
```
prints out:
```
  [] =>
    Thm:
      (-> [b : bool] (= bool ($ Not ($ Not b)) b))
    
    Extract:
      (lam [b] (if b ax (#27 b)))
```

The `#27` here is an internal name that does not make sense to the user, and should not be displayed. @jonsterling and I think it would be better to sanitize the name entirely by replacing it with `???`. If anyone has a good idea for a helpful thing to name it, that might also be reasonable.

**Comment by cangiuli** [comment]
Our new Thought is that we could name it `#0` inside of `Print NotNot.`, and (something like) `NotNot.#0` inside of later extracts.

**Comment by jonsterling** [comment]
We decided to always print it as `#NotNot/0`.
