### ISSUE TITLE
Improve auto to handle line types

### ISSUE THREAD

**Issue by cangiuli** [RedPRL/sml-redprl#548]
Right now, auto cannot prove any basic results about manipulating line types. The following code:

```
Thm Foo : [
  (->
   [ty : (U 0 kan)]
   [p : (line [_] ty)]
   (path [_] ty (@ p 0) (@ p 1)))
] by [
  (lam ty p => abs x => `(@ p x)); auto; ?
].
```

prints out

```
groupoid.prl:7.42-7.43 [Info]:
  ?.
  Goal #0.
    (-> dim ty) match path @ 0
  Goal #1.
    ty : (U 0 kan),
    p : (-> dim ty),
    x : dim
    >> #0 <= ty type
```

**Comment by jonsterling** [comment]
(I realize that to "really" fix this we have to fix the fundamental problems with `auto`, but this seems basic enough that if I train my Thought on it, I ought to be able to fix it in the shorter term. Having line types work properly will make a number of proofs easier.)
