### ISSUE TITLE
Integers, less than, natural numbers, and truncation levels

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-redprl#56]

**Comment by favonia** [comment]
Should we implement natural numbers at the same time?

**Comment by jonsterling** [comment]
@favonia That sounds reasonable! We should think about how we actually want to represent the integers—should it be primitive, or should it use the naturals?

And we should confer with Carlo to decide the specific form of the naturals... My preference would be *strict* naturals / naturals where the compositions compute to the cap or something like that, if possible.

**Comment by favonia** [comment]
Indeed. Firstly, natural numbers and truncation levels should just be subtypes of integers. Secondly, I want both the binary and unary representations, but have to think more about what to do. The motivation is to extract efficient programs that will be appreciated by most computer scientists. By the way, I believe whether it is strict or not is irrelevant to the representation---the difference only lies in the dynamics of `hcom` and we can add `snat` just like `sbool`.

**Comment by jonsterling** [comment]
@favonia thanks, I think what you say makes sense.

**Comment by cangiuli** [comment]
By the way, on paper I was planning on renaming `bool` to `wbool` and `sbool` to `bool`, so that future types can be called `unit`, `nat`, etc. rather than `sunit` and `snat`.

**Comment by jonsterling** [comment]
👍

**Comment by favonia** [comment]
@jonsterling @cangiuli After some internal struggling I now prefer a new parameter sort for integers, along with a new 0-arity operator taking an integer directly from Standard ML's `Intinf` or `Z` from the math textbook. The `nat` PER relates all the non-negative integers. The induction principle for `int` should have three cases, and the principle for `nat` is just a specialized version omitting the negative branch. We could have different symbols for both induction principles, though. The successor `S(n)` is just `n + 1`, etc. Realizers using these induction principles would be terribly inefficient, but later on we can provide a primitive less-than that connects to "real' programming languages as in NuPRL, and one can prove theorems about realizers using the primitive less-than constructs.

How is the above plan?

@jonsterling When shall we rename `BOOL` to `WOOL`... I mean `W_BOOL`?

**Comment by favonia** [comment]
(I changed the above comment. See the updated version on GitHub.)

**Comment by favonia** [comment]
(@jonsterling I changed the above comment. See the updated version on GitHub.)

**Comment by jonsterling** [comment]
@favonia I like that idea, it sounds good for programming(!). I can't remember what @cangiuli said about this—is it ok if we just bung this into redprl? 

Re: bool, let's rename it right away to avoid confusion. I actually kind of like `wool` 🤣

**Comment by favonia** [comment]
@jonsterling We could have a secret rule in the lexer.

**Comment by jonsterling** [comment]
@favonia heh, good idea 😄!

**Comment by cangiuli** [comment]
You could make the surface syntax `w_bool` but use a more Immortal name internally, to pull the `wool` over users' eyes.

**Comment by favonia** [comment]
@cangiuli We should respect those Immortal users who want to type `wool`. As a gesture of goodwill we also take `w_bool`.

**Comment by favonia** [comment]
Alright, but for the printing, at least for the next Tuesday, maybe it should be `w_bool`.

**Comment by favonia** [comment]
Should a realizer of the rational number type just be a tuple?

**Comment by jonsterling** [comment]
@favonia I guess it depends on how we intend to encode the rationals... A tuple sounds perfectly reasonable. Do you need them for an example or something?

**Comment by favonia** [comment]
@jonsterling It's a combination of "why not" and "for fun". Maybe a small library of computational reals or something.

**Comment by jonsterling** [comment]
that would be so cool! I wonder if we can include enough types so that we can define these internally? I guess we would need some kind of quotient.

**Comment by favonia** [comment]
What should be the realizer of `1 < 2`? The trivial realizer? Actually, could we use the same realizer for `any(z)` where `z in void` too?

**Comment by jonsterling** [comment]
@favonia It should be a trivial realizer, but if you are regarding `1<2` as a type, you will need a 'trivial' realizer which lives in the correct sort, namely `EXP`; the `AX` realizer is the sole operator of sort `TRIV`, on the other hand. Feel free to define a new operator...

As for void-elim, my preference is that you also use this realizer for void-elim too, as you suggest. There's no need to keep track of the void variable in the realizer, so we can use the same one.

**Comment by favonia** [comment]
Oh, the sortedness is a good point... I will define another random realizer.

**Comment by favonia** [comment]
So, I guess if one day we internalize the equality, it would have this realizer as well.

**Comment by jonsterling** [comment]
@favonia yes 😄 👍

**Comment by favonia** [comment]
Close this because it seems we can already do what we want except maybe truncation levels. Reopen if you disagree.
