### ISSUE TITLE
Update README with a new section about Vim

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#572]

**Comment by cangiuli** [comment]
Do you mean that it should be more detailed? The README already has a section about Vim: https://github.com/RedPRL/sml-redprl/commit/e260942327d74ca8c5f5d992280323ec725ccd31#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by favonia** [comment]
Sorry I just tried to write down what I remember to do.
