### ISSUE TITLE
travis testing succeeds even if some examples are failing

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#578]
Like https://travis-ci.org/RedPRL/sml-redprl/jobs/337619065. A false positive. @cangiuli @jonsterling

**Comment by jonsterling** [comment]
@cangiuli I just tried it locally and it looks like your script returns a `0` exit code even when one of the tests fails??

**Comment by jonsterling** [comment]
To be more precise, `script/run-tests.sh` returns the correct exit code, but `script/test-mlton.sh` does not.
