### ISSUE TITLE
Funding acknowledgements

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#580]
Should we put the funding acknowledgements somewhere on the website or in the GitHub repo?

**Comment by jonsterling** [comment]
Probably on both...

**Comment by cangiuli** [comment]
> This research was sponsored by the Air Force Office of Scientific Research under grant number FA9550-15-1-0053 and the National Science Foundation under grant number DMS-1638352. We also thank the Isaac Newton Institute for Mathematical Sciences for its support and hospitality during the program "Big Proof" when part of work on this paper was undertaken; the program was supported by the Engineering and Physical Sciences Research Council under grant number EP/K032208/1. The views and conclusions contained in this document are those of the authors and should not be interpreted as representing the official policies, either expressed or implied, of any sponsoring institution, government or any other entity.

**Comment by ecavallo** [comment]
the Big Proof part mentions "work on this paper"

**Comment by jonsterling** [comment]
oops
