### ISSUE TITLE
{foo,bar} should match either (1) tuples with proj1 and proj2 or more, or (2) tuples with foo and bar and more, but definitely nothing else!

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#584]

**Comment by favonia** [comment]
@jonsterling I would suppose the intended semantics is the first one. Any opinion?

**Comment by jonsterling** [comment]
@favonia I just looked, and I guess I forgot how this stuff currently works and was mistaken. The current behavior is to abbreviate `let {proj1=foo, proj2=bar} ...`; with that said, I don't have a strong preference about how this should work, so you can feel free to change it to how you think it should be, if you want.
