### ISSUE TITLE
Print (U 0) instead of (U 0 stable)

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#594]

**Comment by cangiuli** [comment]
Yes. Relatedly, I don't really like the name `stable`; can you explain why you use it instead of `pre`?

**Comment by jonsterling** [comment]
@cangiuli I assume it stands for "stable under dimension substitution". `pre` would be fine with me!

**Comment by favonia** [comment]
I just feel `pre` does not sound like a standalone adjective...? But any native speaker has the power to overwrite my intuition.

**Comment by cangiuli** [comment]
Given that we have `(U 0 hcom)` and `(U 0 coe)`, I think `(U 0 pre)` fits fine -- hcom types, coe types, pre types. (By the way, this is orthogonal to your original issue, which I agree with in any case.)
