### ISSUE TITLE
synthTerm should return aux goals in a separate list

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#595]
At least this is one possible solution to the uncontrolled number of preceding aux goals.

**Comment by jonsterling** [comment]
@favonia I'd like to improve this too; can you clarify what you mean by a `separate list`? As far as I know, *all* the goals returned by `synthTerm` are auxiliary, so there is only one list returned.

**Comment by favonia** [comment]
@jonsterling Just to double check---I put them in a list. It is not "separate" as you mentioned, but I was following my original idea. Hope it is clear what I meant now.

**Comment by jonsterling** [comment]
@favonia I think you did it in a nice way 😄
