### ISSUE TITLE
Path types

### ISSUE THREAD

**Issue by markfarrell** [RedPRL/sml-redprl#62]
:wink: 

- [x] type equality
- [x] path equality
- [x] path introduction
- [x] structural equality
- [x] path-app / type synthesis
- [x] path-app "computation" (open head expansion can't apply here, so we need an equational rule)
- [x] equational rule for projection (i.e. `M@0 = P_0` if `M : paths({x}.A; P_0,P_1)`).

**Comment by jonsterling** [comment]
I'm hoping next year to work on generalizing Red JonPRL to a higher dimensional version of computational type theory, in which case we'll have something analogous to the path type. We'll see! :smile:

**Comment by jonsterling** [comment]
@markfarrell It's going to happen soon!!
