### ISSUE TITLE
Prove the computation rule for J

### ISSUE THREAD

**Issue by mortberg** [RedPRL/sml-redprl#627]
Prove this and add to: https://github.com/RedPRL/sml-redprl/blob/master/example/J.prl

One should do it both for the direct definition of J in the file above and for J defined using contractibility of singletons.

**Comment by mortberg** [comment]
Yes, the computation rule will only hold up to a path. It seems surprisingly complicated to prove this.

**Comment by favonia** [comment]
What should be the statement, actually? There's no reason to believe the endpoints would match. Maybe we should use connection instead and allow at least coe along constant families.

**Comment by mortberg** [comment]
Here's the statement and proof in cubicaltt: https://github.com/mortberg/cubicaltt/blob/master/examples/prelude.ctt#L82

I don't believe the proof goes through as in cubicaltt as the connection in RedPRL is defined using a complicated hcom and there is no reason for it to go away if you plug in refl for p. But as you say it might still be easier to get the proof to go through using the connection as you are then only coercing in a constant family. This is what I meant by it being "surprisingly complicated" to prove this in this system.

**Comment by favonia** [comment]
I wasn't making it clear---the constancy is necessary to make things type check. BTW I think the connection hcom is okay.

**Comment by favonia** [comment]
Actually this turns out to be straightforward in the sense that you can just follow the typing requirement to complete the composition. Is there anything special about the contractibility of singletons? My current understanding is that it is exactly the same as using connections, and if `J` was done using connections then there is nothing to do in `J/comp`.

**Comment by mortberg** [comment]
Can you do the other proof as well please? Preferably using your complicated connection from https://github.com/RedPRL/sml-redprl/blob/master/example/connection.prl#L1

I think that the problem is that J defined this way is  

``coe 0->1 (<i> fam (p @ i) (connectionAnd A a x p @ i)) d``

so that when you plug in `<_> a` for p you end up with a similar problem as with the other J: you cannot prove the equality using a `coe 0->j` as the family in the term is not constantly `fam a (<_> a)` as required for the computation rule for J...

**Comment by favonia** [comment]
> you cannot prove the equality using a coe 0->j as the family in the term is not constantly fam a (<_> a)

You are right. I did not think it through carefully.

**Comment by mortberg** [comment]
I also thought that this proof would just go through the same way as in cubicaltt, but the fact that the family has to be constant makes it a lot more subtle. This is why one should always formalize everything :)

**Comment by favonia** [comment]
@mortberg Should we close this now?

**Comment by mortberg** [comment]
Yeah, unless you want to do the computation rule for J defined using a connection

**Comment by favonia** [comment]
Nah, that's an exercise for future students.
