### ISSUE TITLE
Print integers as (int i).

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#628]
Currently the printer is not a section of parser when it comes to integers. An easy solution is to print integers as `(int i)` where numbers by default will be dimension constants. It also makes `(nat i)` natural and solves #590 completely.

**Comment by cangiuli** [comment]
I'm OK with printing that way. Can you explain what this has to do with #590?

**Comment by favonia** [comment]
@cangiuli The practical reason why `nat` is a subtype of `int` is to allow users to write numerals `3` for both types. If we are writing the numbers as `(int 3)` and `(nat 3)`, then there is no need to make `nat` a subtype of `int`, and so their recursor can be reverted back to something more systematic. In other words, `int` can just be the normal `nat + nat`.

**Comment by favonia** [comment]
(Why wasn't this issue closed automatically? I thought "Solve" is a keyword.)

**Comment by jonsterling** [comment]
@favonia I think it accepts "resolve", not sure about solve.
