### ISSUE TITLE
Linear types

### ISSUE THREAD

**Issue by ak3n** [RedPRL/sml-redprl#63]
Can I join the types party? I am learning linear logic right now, how does linear types refer to CTT?

**Comment by jonsterling** [comment]
I have been hoping that we could add linear types to CTT as well.

The *semantics* of a linear extension to CTT's PER (partial equivalence relations) model are clear; essentially, these types classify (are PERs on) machine states (store + term).

However, I am not certain how we want it to look in the proof theory / PRL. One option would be to add a linear context to the sequents.
