### ISSUE TITLE
Better freshing/renaming?

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#640]
Right now freshing is often followed by renaming in a single rule. Take the function type as an example, to prove that two function types are the same, two freshings are done and then two renamings are done to use the new symbol instead. I wonder if this contributes to slowness, and if there's a way to merge these two steps to reduce abt rebuilds.

**Comment by jonsterling** [comment]
It should be possible to optimize this; ultimately, even doing these things *once* is going to be unbearably slow, but I guess there's no reason for us to do it twice unnecessarily :smile:

**Comment by favonia** [comment]
Are we postponing this to RedPRL 2 then? I think the API would be something which takes a list of variable for refreshing.

**Comment by jonsterling** [comment]
The renaming stuff is easy enough that it can be done right away (as soon as anyone has time)

**Comment by favonia** [comment]
Actually, it might be helpful if...

1. The view uses `abs` instead `abt`. The avoids refreshing.
2. There are two APIs: substitution for `abs` (already there) and unsafe operator to open up an abstraction without any renaming.

This way we can avoid unnecessary refreshing.
