### ISSUE TITLE
Change the syntax of Thm?

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#645]
Use something like
```
Thm X in A by [ ... ]
```
or
```
Thm X : A by [ ... ]
```
instead of
```
Thm X : [ A ] by [ ... ]
```

**Comment by jonsterling** [comment]
The second one is probably alright!

**Comment by jonsterling** [comment]
@favonia I'm experimenting with a bracket-free notation in my PR #650... It seems much more elegant.
