### ISSUE TITLE
Bug in HCom.Eq

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-redprl#664]
While documenting our rules, @timjb noticed that the [`HCom.Eq` rule](https://github.com/RedPRL/sml-redprl/blob/d08b0937242685ed80ae3fd73e5484c3aa8dea1c/src/redprl/refiner_composition_kit.fun#L152) does not seem to be checking that the type arguments of the two compositions are equal. This seems wrong to me, but I might be confused...

@favonia Do we need to change the subgoal?

**Comment by favonia** [comment]
Yes. It is a bug introduced in cd276c017013efa73ad2dd859fb8c422e24ed9c5 (sorry) and should be fixed.

**Comment by jonsterling** [comment]
@favonia OK! I think it's easy to fix.
