### ISSUE TITLE
Complete rename to RedPRL

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-redprl#69]
- [x] rename org
- [x] rename repo
- [x] update README
- [x] rename files
- [x] purchase `redprl.org`
- [x] set up github pages on `redprl.org` (as separate repo)

**Comment by scott-fleischman** [comment]
👍
Looks like the GitHub org site still points to jonprl.org

**Comment by jonsterling** [comment]
oh, thanks for noticing!
