### ISSUE TITLE
"Compile SML raised: Option" on initial build

### ISSUE THREAD

**Issue by shingarov** [RedPRL/sml-redprl#696]
Trying to build a newly-cloned RedPRL, (using today's git master mlton), results in the attached exception.
[typescript.txt](https://github.com/RedPRL/sml-redprl/files/3221567/typescript.txt)

**Comment by MatthewFluet** [comment]
That's an internal compiler error; could you open an issue at https://github.com/MLton/mlton?

**Comment by MatthewFluet** [comment]
Reported as MLton/mlton#305 and to be closed by MLton/mlton#306.

**Comment by shingarov** [comment]
rebuilding now to see that it indeed solves this issue...

**Comment by shingarov** [comment]
Verified as fixed.
